SELECT ZE_SEGREG, * FROM SZE010
WHERE D_E_L_E_T_ = ''
AND ZE_STATUS != 'C'
AND ZE_FILIAL = '01'
AND ZE_SAFRA = '2024'
and ZE_CARGA = '0034'

select * FROM VA_VEVENTOS
where SAFRA = '2024' and FILIAL = '01' and CARGA_SAFRA = '0034'
