SELECT COUNT (*), SUM (ZI_VALOR)
FROM SZI010 
--BEGIN TRAN; UPDATE SZI010 SET D_E_L_E_T_ = '*', R_E_C_D_E_L_ = R_E_C_N_O_
WHERE D_E_L_E_T_ = ''
AND ZI_DATA = '20230831'
and ZI_TM = '24'
--order by R_E_C_N_O_


SELECT COUNT (*), SUM (E2_VALOR)
FROM SE2010
--BEGIN TRAN; UPDATE SE2010 SET D_E_L_E_T_ = '*', R_E_C_D_E_L_ = R_E_C_N_O_
WHERE D_E_L_E_T_ = ''
AND E2_FILIAL = '01'
AND E2_PREFIXO = 'MUD'
AND E2_EMISSAO = '20230831'
--order by R_E_C_N_O_

--COMMIT
