SELECT PRODUTO, DESCRI_PRODUTO, 
	SUM (ESTQ_LITROS_TOTAL), SUM (ESTQ_LITROS_GRANEL), SUM (ESTQ_LITROS_ENVASADO)
FROM dbo.VA_FESTOQUES_LITROS ('20230930', '01', '01')
where ESTQ_LITROS_GRANEL != 0
and PRODUTO in ('2776','30206')
GROUP BY PRODUTO, DESCRI_PRODUTO
ORDER BY PRODUTO

-- DIFERENCA NO ITEM 2776, 30206

SELECT B9_COD
      ,B9_DATA
      ,B9_FILIAL
      ,B9_LOCAL
      ,BK_LOCALIZ
      ,BK_LOTECTL
      ,BK_QINI
      FROM SB1010 SB1, SB9010 SB9
		LEFT JOIN SBK010 SBK
		ON (SBK.D_E_L_E_T_ = ''
		AND SBK.BK_FILIAL = SB9.B9_FILIAL
		AND SBK.BK_COD = SB9.B9_COD
		AND SBK.BK_LOCAL = SB9.B9_LOCAL
		AND SBK.BK_QINI != 0
		)
WHERE SB9.D_E_L_E_T_ = ''
AND SB9.B9_FILIAL != '02'  -- FILIAL ENCERRADA MAS FICARAM SALDOS ANTIGOS NO SISTEMA
AND SB9.B9_DATA >= '20160101'  -- OPTAMOS POR NAO LER DADOS ANTES DISSO
AND SB9.B9_QINI != 0
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_FILIAL = '  '
AND SB1.B1_COD = SB9.B9_COD
and SB1.B1_TIPO = 'VD'
AND SB9.B9_DATA = '20230930' AND SB9.B9_FILIAL = '01'
AND SBK.BK_LOCALIZ IS NULL
