SELECT ORDEM, DESC_N1, DESC_N2, NIVEL
	, FORMAT (SUM (REA_PER), 'N2', 'PT-BR')
FROM DRE
WHERE ANO = '2023'
and NIVEL <= 1
group by ORDEM, DESC_N1, DESC_N2, NIVEL
ORDER BY ordem, DESC_N1, DESC_N2, NIVEL


