-- CREATE VIEW [dbo].[VA_VRENDIMENTOS_VINIFICACAO2] AS 
-- Cooperativa Agroindustrial Nova Alianca Ltda
-- View para buscar dados de rendimentos de OPs de vinificacao
-- Autor: Robert Koch
-- Data:  24/01/2024
--
-- Historico de alteracoes:
-- 22/02/2024 - Robert - Criada coluna CONSUMO_MAO_OBRA_CUSTO
-- 05/03/2024 - Robert - Reordenadas colunas.
--

/*
-- MONTA UMA LISTA DAS OPS DE VINIFICACAO
SELECT
		SD3.D3_FILIAL AS FILIAL
	   ,SD3.D3_OP AS OP
	   ,MIN(SD3.D3_EMISSAO) AS PRIMEIRO_MOVTO
	   ,MAX(SD3.D3_EMISSAO) AS ULTIMO_MOVTO
	INTO #LISTA_DE_OPS
	FROM SD3010 SD3
	WHERE SD3.D_E_L_E_T_ = ''
	AND SD3.D3_ESTORNO = ''
	AND SD3.D3_CF LIKE 'RE%'
	AND SD3.D3_GRUPO = '0400'
	GROUP BY SD3.D3_FILIAL, SD3.D3_OP
*/
WITH OPS_DE_VINIFICACAO AS
(
	SELECT SUBSTRING (OPV.ULTIMO_MOVTO, 1, 4) AS SAFRA
		, OPV.FILIAL, OPV.OP
		, OPV.PRIMEIRO_MOVTO, OPV.ULTIMO_MOVTO
		, SD3.D3_COD AS COD_PRODUZIDO
		, SB1.B1_DESC AS DESCR_PRODUZIDO
		, SUM (SD3.D3_QUANT * SB1.B1_LITROS) AS TOT_PRODUZIDO_LITROS
		, SUM (SD3.D3_CUSTO1) AS TOT_PRODUZIDO_CUSTO_MEDIO
	FROM #LISTA_DE_OPS OPV
		LEFT JOIN SD3010 SD3
			LEFT JOIN SB1010 SB1
				ON (SB1.D_E_L_E_T_ = ''
				AND SB1.B1_FILIAL = '  '
				AND SB1.B1_COD = SD3.D3_COD)
			ON (SD3.D_E_L_E_T_ = ''
			AND SD3.D3_FILIAL = OPV.FILIAL
			AND SD3.D3_OP = OPV.OP
			AND SD3.D3_CF LIKE 'PR%'
			AND SD3.D3_ESTORNO = '')
	WHERE OPV.FILIAL = '01' AND OPV.ULTIMO_MOVTO >= '20240101' --AND OP = '13799301001   '
	GROUP BY SUBSTRING (OPV.ULTIMO_MOVTO, 1, 4)
		, OPV.FILIAL, OPV.OP
		, OPV.PRIMEIRO_MOVTO, OPV.ULTIMO_MOVTO
		, SD3.D3_COD, SB1.B1_DESC
)
-- SELECT * FROM OPS_DE_VINIFICACAO
--, MOVTOS AS (
SELECT OPV.*
	, CASE WHEN SD3.D3_GRUPO = '0400' THEN SD3.D3_QUANT ELSE 0 END AS CONSUMO_UVA_KG
	, CASE WHEN SD3.D3_GRUPO = '0400' THEN SD3.D3_CUSTO1 ELSE 0 END AS CONSUMO_UVA_CUSTO
	--, CASE WHEN SD3.D3_TIPO = 'PS' AND SB1.B1_DESC LIKE 'ACUCAR%' THEN SD3.D3_QUANT ELSE 0 END AS CONSUMO_ACUCAR_KG
	--, CASE WHEN SD3.D3_TIPO = 'PS' AND SB1.B1_DESC LIKE 'ACUCAR%' THEN SD3.D3_CUSTO1 ELSE 0 END AS CONSUMO_ACUCAR_CUSTO
	--, CASE WHEN SD3.D3_TIPO = 'PS' AND SB1.B1_DESC NOT LIKE 'ACUCAR%' THEN SD3.D3_QUANT ELSE 0 END AS CONSUMO_INSUMOS_KG
	--, CASE WHEN SD3.D3_TIPO = 'PS' AND SB1.B1_DESC NOT LIKE 'ACUCAR%' THEN SD3.D3_CUSTO1 ELSE 0 END AS CONSUMO_INSUMOS_CUSTO
	, CASE WHEN SD3.D3_TIPO IN ('AO', 'GF', 'AP') THEN SD3.D3_QUANT ELSE 0 END AS CONSUMO_MAO_OBRA_QT
	, CASE WHEN SD3.D3_TIPO IN ('AO', 'GF', 'AP') THEN SD3.D3_CUSTO1 ELSE 0 END AS CONSUMO_MAO_OBRA_CUSTO
FROM OPS_DE_VINIFICACAO OPV
	, SD3010 SD3
	--	LEFT JOIN SB1010 SB1
	--		ON (SB1.D_E_L_E_T_ = ''
	--		AND SB1.B1_FILIAL = '  '
	--		AND SB1.B1_COD = SD3.D3_COD)
		where SD3.D_E_L_E_T_ = ''
		AND SD3.D3_FILIAL = OPV.FILIAL
		AND SD3.D3_OP = OPV.OP
		AND SD3.D3_CF LIKE 'RE%'
		AND SD3.D3_ESTORNO = ''
--)
--SELECT * FROM MOVTOS

--	, ROUND (PRODUZIDO_LITROS / CONSUMO_UVA_KG, 2) AS RENDIMENTO
