-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- opcao de escolher se quer ver quantidades (litragem) ou valores (custos)

-- CRIA UMA SDT INICIAL PARA CLASSIFICAR TIPOS DE MOVIMENTOS E TIPOS DE ITENS
WITH DADOS_OP AS (
	SELECT SD3.D3_FILIAL
		, SD3.D3_OP
		, SC2.C2_PRODUTO
		, SD3.D3_VAPEROP
		, SD3.D3_COD
		, SD3.D3_QUANT
		, SD3.D3_CUSTO1
		, CASE WHEN SD3.D3_CF LIKE 'PR%'
			THEN 'P'
			ELSE CASE WHEN SD3.D3_CF LIKE 'RE%'
				THEN 'C'
				ELSE 'O'
				END
			END AS CLASSIF_MOVTO
		, CASE WHEN SD3.D3_TIPO IN ('AP', 'MO', 'GF')
			THEN 'MOB'
			ELSE CASE WHEN SD3.D3_TIPO IN ('MP','VD','ME','PP','UC','BN')
				THEN SD3.D3_TIPO
				ELSE 'OUT'
				END
			END AS CLASSIF_ITEM
	FROM SD3010 SD3
		-- Nao sei por que motivo o otimizador do SQL costuma escolher indices ruins para o SD3
		WITH (INDEX (SD30106))
		, SB1010 SB1
		, SC2010 SC2
	WHERE SD3.D_E_L_E_T_ = ''
	AND SD3.D3_FILIAL    = '01'
	AND SD3.D3_EMISSAO  >= '20200101'  -- PARA NAO OLHAR OPS MUITO ANTIGAS
	AND SD3.D3_ESTORNO   = ''
	AND SD3.D3_OP       != ''
	AND SB1.D_E_L_E_T_   = ''
	AND SB1.B1_FILIAL    = '  '
	AND SB1.B1_COD       = SD3.D3_COD
	AND SC2.D_E_L_E_T_   = ''
	AND SC2.C2_FILIAL    = SD3.D3_FILIAL
	AND SC2.C2_NUM       = SUBSTRING (SD3.D3_OP, 1, 6)
	AND SC2.C2_ITEM      = SUBSTRING (SD3.D3_OP, 7, 2)
	AND SC2.C2_SEQUEN    = SUBSTRING (SD3.D3_OP, 9, 3)
	AND SC2.C2_ITEMGRD   = SUBSTRING (SD3.D3_OP, 12, 2)
	AND SC2.C2_PRODUTO  != 'MANUTENCAO'

	-- TESTES
	and SD3.D3_EMISSAO >= '20240101'
--	AND SC2.C2_PRODUTO IN ('0345','0082','0151', '2859', '2203') AND C2_EMISSAO LIKE '2024%'

), C AS (
	SELECT D3_FILIAL
		, D3_OP
		, C2_PRODUTO
		, D3_VAPEROP
		, D3_COD
		, D3_QUANT
		, D3_CUSTO1
		, CLASSIF_MOVTO
		, CLASSIF_ITEM
		, SUM (CASE WHEN CLASSIF_MOVTO = 'P' THEN D3_QUANT  ELSE 0 END) AS QT_PRODUZIDA
		, SUM (CASE WHEN CLASSIF_MOVTO = 'P' THEN D3_CUSTO1 ELSE 0 END) AS CUSTO_PRODUCAO
		, SUM (CASE WHEN CLASSIF_MOVTO = 'C' THEN D3_CUSTO1 ELSE 0 END) AS CUSTO_REQUISICAO
	FROM DADOS_OP
	GROUP BY D3_FILIAL
		, D3_OP
		, C2_PRODUTO
		, D3_VAPEROP
		, D3_COD
		, D3_QUANT
		, D3_CUSTO1
		, CLASSIF_MOVTO
		, CLASSIF_ITEM
)
SELECT C.*
	--, RTRIM (B1_DESC) AS DESC_PROD_FINAL
	, C.QT_PRODUZIDA * SB1.B1_LITROS AS LITROS_PRODUZIDOS
	--, RTRIM (ZX5_39.ZX5_39DESC) AS LINHA_COML
	, SB1.B1_CODLIN
FROM C
	, SB1010 SB1
--	LEFT JOIN ZX5010 ZX5_39
--		ON (ZX5_39.ZX5_TABELA = '39'
--		AND ZX5_39.ZX5_39COD = SB1.B1_CODLIN)
WHERE SB1.D_E_L_E_T_ = ''
AND SB1.B1_FILIAL    = '  '
AND SB1.B1_COD       = C.C2_PRODUTO
