WITH DATA_INICIAL AS (
	SELECT '20200101' AS DATAINI
)
, OPV AS (
	SELECT *
	FROM VA_VOPS_DE_VINIFICACAO
	WHERE ULTIMO_MOVTO >= (SELECT DATAINI FROM DATA_INICIAL)
)
, SD3_BASE AS (
	SELECT SD3.D3_FILIAL, SD3.D3_OP, SD3.D3_VAPEROP, SD3.D3_COD, D3_QUANT, SD3.D3_UM, D3_CUSTO1, SD3.D3_CF, SD3.D3_TIPO, SD3.D3_EMISSAO, SD3.D3_GRUPO
	FROM SD3010 SD3
		, SC2010 SC2
	WHERE SD3.D_E_L_E_T_ = ''
	AND SD3.D3_EMISSAO  >= '20200101'  -- PARA NAO OLHAR OPS MUITO ANTIGAS
	AND SD3.D3_ESTORNO   = ''
	AND SD3.D3_OP       != ''
	AND SD3.D3_ORDEM     = ''  -- SE D3_ORDEM ESTIVER PREENCHIDO, TRATA-SE DE ORDEM DE SERVICO DA MANUTENCAO.
	AND SC2.D_E_L_E_T_   = ''
	AND SC2.C2_FILIAL    = SD3.D3_FILIAL
	AND SC2.C2_NUM       = SUBSTRING (SD3.D3_OP, 1, 6)
	AND SC2.C2_ITEM      = SUBSTRING (SD3.D3_OP, 7, 2)
	AND SC2.C2_SEQUEN    = SUBSTRING (SD3.D3_OP, 9, 3)
	AND SC2.C2_ITEMGRD   = SUBSTRING (SD3.D3_OP, 12, 2)
	AND SC2.C2_VAOPESP   NOT IN ('R', 'E', 'T')  -- POR ENQUANTO, QUERO APENAS ORDENS NORMAIS.

	and SD3.D3_EMISSAO >= '20231201'  -- PARA NAO CARREGAR MUITA COISA ENQUANTO ESTOU DESENVOLVENDO O RELATORIO.
)
, SD3_PRODUCAO AS (
	SELECT D3_FILIAL AS FILIAL, D3_OP AS OP, D3_TIPO AS TIPO_PROD_FINAL, D3_COD AS PROD_FINAL, D3_UM AS UN_MED_PROD_FINAL
		, SUM (D3_QUANT) AS QT_PRODUZIDA
		, SUM (D3_CUSTO1) AS CUSTO_PRODUCAO
		, MAX (D3_EMISSAO) AS DATA_ENCERRAMENTO
	FROM SD3_BASE
	WHERE D3_CF LIKE 'PR%'
	GROUP BY D3_FILIAL, D3_OP, D3_COD, D3_TIPO, D3_UM
)
, DADOS_OP AS (
	SELECT SD3_PRODUCAO.FILIAL
		, SD3_PRODUCAO.OP
		, CAST (SD3_PRODUCAO.DATA_ENCERRAMENTO + ' 00:00' AS DATE) AS DATA_ENCERRAMENTO
		, SD3_PRODUCAO.TIPO_PROD_FINAL
		, SD3_PRODUCAO.PROD_FINAL
		, SD3_PRODUCAO.QT_PRODUZIDA
		, SD3_PRODUCAO.UN_MED_PROD_FINAL
		, SD3_BASE.D3_TIPO AS TIPO_COMPONENTE
		, SD3_BASE.D3_COD AS COMPONENTE
		, SUM (D3_QUANT) AS QT_REQUISITADA
		, SUM (D3_CUSTO1) AS CUSTO_REQUISICAO
		, SD3_BASE.D3_UM AS UN_MED_COMPONENTE
		, CASE D3_VAPEROP WHEN 'S' THEN 'S' ELSE 'N' END AS PERDA
	FROM SD3_BASE
		, SD3_PRODUCAO
	WHERE SD3_BASE.D3_FILIAL = SD3_PRODUCAO.FILIAL
	AND SD3_BASE.D3_OP = SD3_PRODUCAO.OP
	AND SD3_BASE.D3_CF LIKE 'RE%'
	GROUP BY SD3_PRODUCAO.FILIAL
		, SD3_PRODUCAO.OP
		, SD3_PRODUCAO.DATA_ENCERRAMENTO
		, SD3_PRODUCAO.TIPO_PROD_FINAL
		, SD3_PRODUCAO.PROD_FINAL
		, SD3_PRODUCAO.QT_PRODUZIDA
		, SD3_PRODUCAO.UN_MED_PROD_FINAL
		, SD3_BASE.D3_FILIAL
		, SD3_BASE.D3_OP
		, SD3_BASE.D3_COD
		, SD3_BASE.D3_TIPO
		, SD3_BASE.D3_UM
		, SD3_BASE.D3_GRUPO
		, SD3_BASE.D3_VAPEROP
)
SELECT DADOS_OP.*
	, CASE WHEN OPV.OP IS NULL THEN 'N' ELSE 'S' END AS EH_OP_VINIFICACAO
	, SB1_PROD_FINAL.B1_CODLIN AS LINHA_COML_PRODUZIDO
	, DADOS_OP.QT_PRODUZIDA * SB1_PROD_FINAL.B1_LITROS AS LITROS_PRODUZIDOS
	, DADOS_OP.QT_REQUISITADA * SB1_COMPONENTE.B1_LITROS AS LITROS_REQUISITADOS
FROM DADOS_OP
	LEFT JOIN OPV
		ON (OPV.FILIAL = DADOS_OP.FILIAL
		AND OPV.OP = DADOS_OP.OP)

	LEFT JOIN SB1010 SB1_PROD_FINAL
	ON (SB1_PROD_FINAL.D_E_L_E_T_ = ''
	AND SB1_PROD_FINAL.B1_FILIAL = '  '
	AND SB1_PROD_FINAL.B1_COD = DADOS_OP.PROD_FINAL)

	LEFT JOIN SB1010 SB1_COMPONENTE
	ON (SB1_COMPONENTE.D_E_L_E_T_ = ''
	AND SB1_COMPONENTE.B1_FILIAL = '  '
	AND SB1_COMPONENTE.B1_COD = DADOS_OP.COMPONENTE)

--	ORDER BY FILIAL, OP, COMPONENTE, PERDA
