SELECT PRODUTO, SIST_CONDUCAO, COUNT (*),
	ROUND(SUM(PESO_LIQ * GRAU) / SUM(PESO_LIQ), 1) AS GRAU_MEDIO
FROM VA_VNOTAS_SAFRA
WHERE SAFRA = '2023'
AND TIPO_NF IN ('C', 'P')
AND PRODUTO IN ('9852', '9908')
--AND PRODUTO = '9908'
GROUP BY PRODUTO, SIST_CONDUCAO
ORDER BY PRODUTO, SIST_CONDUCAO
;
SELECT SIST_CONDUCAO, COUNT (*), ROUND(SUM(PESO_LIQ * GRAU) / SUM(PESO_LIQ), 1) AS GRAU_MEDIO
FROM VA_VNOTAS_SAFRA
WHERE SAFRA = '2023'
AND TIPO_NF IN ('C', 'P')
AND PRODUTO = '9852'
GROUP BY SIST_CONDUCAO


