-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- opcao de escolher se quer ver quantidades (litragem) ou valores (custos)
WITH C AS (
	SELECT SD3.D3_FILIAL, SD3.D3_OP, SD3.D3_VAPEROP, SC2.C2_PRODUTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'PR%' THEN D3_QUANT ELSE 0 END) AS QT_PRODUZIDA
		, SUM (CASE WHEN SD3.D3_CF LIKE 'PR%' THEN D3_CUSTO1 ELSE 0 END) AS CUSTO_PRODUCAO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'AP' THEN D3_CUSTO1 ELSE 0 END) AS REQ_AP_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'MO' THEN D3_CUSTO1 ELSE 0 END) AS REQ_MO_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'GF' THEN D3_CUSTO1 ELSE 0 END) AS REQ_GF_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'MP' THEN D3_CUSTO1 ELSE 0 END) AS REQ_MP_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'VD' THEN D3_CUSTO1 ELSE 0 END) AS REQ_VD_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'ME' THEN D3_CUSTO1 ELSE 0 END) AS REQ_ME_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'PP' THEN D3_CUSTO1 ELSE 0 END) AS REQ_PP_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'UC' THEN D3_CUSTO1 ELSE 0 END) AS REQ_UC_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'BN' THEN D3_CUSTO1 ELSE 0 END) AS REQ_BN_CUSTO
		, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO NOT IN ('AP','MO','GF','MP','VD','ME','PP','UC','BN') THEN D3_CUSTO1 ELSE 0 END) AS REQ_OUTROS_CUSTO
	FROM SD3010 SD3
		, SB1010 SB1
		, SC2010 SC2
	WHERE SD3.D_E_L_E_T_ = ''
	AND SD3.D3_FILIAL    = '01'
	AND SD3.D3_EMISSAO  >= '20180101'
	AND SD3.D3_ESTORNO  = ''
	AND SD3.D3_OP      != ''
	AND SB1.D_E_L_E_T_  = ''
	AND SB1.B1_FILIAL   = '  '
	AND SB1.B1_COD      = SD3.D3_COD
	AND SC2.D_E_L_E_T_  = ''
	AND SC2.C2_FILIAL   = SD3.D3_FILIAL
	AND SC2.C2_NUM      = SUBSTRING (SD3.D3_OP, 1, 6)
	AND SC2.C2_ITEM     = SUBSTRING (SD3.D3_OP, 7, 2)
	AND SC2.C2_SEQUEN   = SUBSTRING (SD3.D3_OP, 9, 3)
	AND SC2.C2_ITEMGRD  = SUBSTRING (SD3.D3_OP, 12, 2)
	AND SC2.C2_PRODUTO != 'MANUTENCAO'

	-- TESTES
	AND SC2.C2_PRODUTO IN ('0345','0082','0151', '2859', '2203') AND C2_EMISSAO LIKE '2024%'

GROUP BY SD3.D3_FILIAL
	, SD3.D3_OP, SD3.D3_VAPEROP
	, SC2.C2_PRODUTO
)
SELECT C.*
	, RTRIM (B1_DESC) AS DESC_PROD_FINAL
	, C.QT_PRODUZIDA * SB1.B1_LITROS AS LITROS_PRODUZIDOS
	, RTRIM (ZX5_39.ZX5_39DESC) AS LINHA_COML
FROM C
	, SB1010 SB1
	LEFT JOIN ZX5010 ZX5_39
		ON (ZX5_39.ZX5_TABELA = '39'
		AND ZX5_39.ZX5_39COD = SB1.B1_CODLIN)
WHERE SB1.D_E_L_E_T_ = ''
AND SB1.B1_FILIAL    = '  '
AND SB1.B1_COD       = C.C2_PRODUTO


