--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
/*
	SELECT DISTINCT FILIAL, OP
	INTO #OPS_VINIFICACAO
	FROM VA_VDADOS_OP
	WHERE GRUPO = '0400'
	AND TIPO_MOVTO = 'C'
	AND FINALIDADE_OP = 'N'
	AND DATA >= '20210101'
	--AND DATA >= '20240101'
	AND FILIAL IN ('01', '03', '07', '09')
*/

SELECT V.FILIAL, SUBSTRING (V.DATA, 1, 4) AS ANO, V.OP, V.PROD_FINAL, V.DESC_PROD_FINAL, V.LITROS, V.CUSTO
FROM VA_VDADOS_OP V, VA_VOPS_DE_VINIFICACAO OPV
WHERE V.FILIAL = OPV.FILIAL
AND V.OP = OPV.OP
AND V.TIPO_MOVTO = 'P'

SELECT V.FILIAL, SUBSTRING (V.DATA, 1, 4) AS ANO, V.OP, V.PROD_FINAL, V.DESC_PROD_FINAL, V.CODIGO, V.DESCRICAO, V.CUSTO
FROM VA_VDADOS_OP V, #OPS_VINIFICACAO
WHERE V.FILIAL = #OPS_VINIFICACAO.FILIAL
AND V.OP = #OPS_VINIFICACAO.OP
AND V.TIPO_MOVTO = 'C'
AND V.TIPO_PRODUTO IN ('AP','MO','GF')

