SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
;WITH C AS (
SELECT SAFRA, PRODUTO, DESCRICAO
	, SUM (PESO_LIQ) AS PESO
	, CAST (SUM (PESO_LIQ * GRAU) / SUM (PESO_LIQ) AS DECIMAL (4, 1)) AS GRAU_MEDIO
FROM VA_VNOTAS_SAFRA
WHERE SAFRA >= '2018'
GROUP BY DESCRICAO, PRODUTO, SAFRA
)
SELECT DESCRICAO
	, SUM (CASE WHEN SAFRA = '2018' THEN PESO       ELSE 0 END) AS KG_2018
	, SUM (CASE WHEN SAFRA = '2018' THEN GRAU_MEDIO ELSE 0 END) AS GM_2018
	, SUM (CASE WHEN SAFRA = '2019' THEN PESO       ELSE 0 END) AS KG_2019
	, SUM (CASE WHEN SAFRA = '2019' THEN GRAU_MEDIO ELSE 0 END) AS GM_2019
	, SUM (CASE WHEN SAFRA = '2020' THEN PESO       ELSE 0 END) AS KG_2020
	, SUM (CASE WHEN SAFRA = '2020' THEN GRAU_MEDIO ELSE 0 END) AS GM_2020
	, SUM (CASE WHEN SAFRA = '2021' THEN PESO       ELSE 0 END) AS KG_2021
	, SUM (CASE WHEN SAFRA = '2021' THEN GRAU_MEDIO ELSE 0 END) AS GM_2021
	, SUM (CASE WHEN SAFRA = '2022' THEN PESO       ELSE 0 END) AS KG_2022
	, SUM (CASE WHEN SAFRA = '2022' THEN GRAU_MEDIO ELSE 0 END) AS GM_2022
	, SUM (CASE WHEN SAFRA = '2023' THEN PESO       ELSE 0 END) AS KG_2023
	, SUM (CASE WHEN SAFRA = '2023' THEN GRAU_MEDIO ELSE 0 END) AS GM_2023
FROM C
GROUP BY DESCRICAO, PRODUTO
ORDER BY DESCRICAO, PRODUTO
