SELECT * FROM SB9010
--begin tran; update SB9010 set D_E_L_E_T_ = '*', R_E_C_D_E_L_ = R_E_C_N_O_
WHERE D_E_L_E_T_ = ''
AND NOT EXISTS (SELECT
*
FROM NNR010 NNR
WHERE NNR.D_E_L_E_T_ = ''
AND NNR.NNR_FILIAL = ' '
AND NNR.NNR_CODIGO = B9_LOCAL)
--COMMIT



SELECT * FROM SB2010
--begin tran; update SB2010 set D_E_L_E_T_ = '*', R_E_C_D_E_L_ = R_E_C_N_O_
WHERE D_E_L_E_T_ = ''
AND NOT EXISTS (SELECT
*
FROM NNR010 NNR
WHERE NNR.D_E_L_E_T_ = ''
AND NNR.NNR_FILIAL = ' '
AND NNR.NNR_CODIGO = B2_LOCAL)
--COMMIT

