select * FROM ZX5010
--BEGIN TRAN; UPDATE ZX5010 SET D_E_L_E_T_ = '*', R_E_C_D_E_L_ = R_E_C_N_O_
WHERE D_E_L_E_T_ = ''
AND ZX5_TABELA = '13'
AND ZX5_13SAFR = 'SJ23'
--COMMIT

select * FROM ZX5010
--BEGIN TRAN; UPDATE ZX5010 SET D_E_L_E_T_ = '*', R_E_C_D_E_L_ = R_E_C_N_O_
WHERE D_E_L_E_T_ = ''
AND ZX5_TABELA = '14'
AND ZX5_14SAFR = 'SJ23'
--COMMIT
