-- EXEMPLO DE UMA NECESSIDADE DE MANUTENCAO, UM PLANO E UMA OS DESSE PLANO, QUE GERAMOS NA BASE TESTE:
SELECT TOP 3 * FROM STF010 ORDER BY R_E_C_N_O_ DESC
SELECT TOP 1 * FROM STI010 ORDER BY R_E_C_N_O_ DESC
SELECT * FROM VA_VDADOS_OS WHERE FILIAL = '01' AND ORDEM = '027184'

-- EXEMPLO DE TODAS AS NECESSIDADES DE MANUTENCAO DE UM DETERMINADO BEM:
SELECT * FROM STF010 WHERE D_E_L_E_T_ = '' AND TF_ATIVO = 'S'
AND TF_CODBEM = 'ECH-004-01-0001 '
ORDER BY TF_CODBEM, TF_SERVICO

-- LISTA DE TIPOS DE SERVICO:
SELECT * FROM ST4010 WHERE D_E_L_E_T_ = '' ORDER BY T4_SERVICO

-- LISTA DE PLANOS QUE ATENDEM DETERMINADO BEM x DETERMINADO TIPO DE SERVICO:
SELECT * FROM STI010 WHERE D_E_L_E_T_ = ''
AND TI_BEMINI <= 'ECH-004-01-0001 ' AND TI_BEMFIM >= 'ECH-004-01-0001 '
AND TI_SERVINI <= '026' AND TI_SERVFIM >= '026'

