/*
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- drop TABLE #OPS;
SELECT * 
into #OPS
FROM VA_VOPS_DE_VINIFICACAO
WHERE FILIAL IN ('01','03','07')
AND PRIMEIRO_MOVTO like '2024%'
;
CREATE NONCLUSTERED INDEX OPS_IDX1 ON #OPS (FILIAL, OP)
*/
--SELECT * FROM #OPS
;
-- DROP TABLE #OPS_SAFRA
SELECT PROD_FINAL
	, V.DESC_PROD_FINAL
	, (SELECT SUM (D3_QUANT)
		FROM SD3010 SD3
		WHERE SD3.D_E_L_E_T_ = ''
		AND SD3.D3_CF LIKE 'PR%'
		AND SD3.D3_EMISSAO LIKE '2024%'
		AND SD3.D3_COD = V.PROD_FINAL
		AND SD3.D3_ESTORNO = ''
		AND EXISTS (SELECT *
					FROM #OPS OPV --VA_VOPS_DE_VINIFICACAO OPV
					WHERE OPV.FILIAL = SD3.D3_FILIAL
					AND OPV.OP = SD3.D3_OP)
		) AS QT_PRODUZIDA
	, V.TIPO_PRODUTO
	, V.GRUPO
	, V.CODIGO
	, V.DESCRICAO
	, SUM (QUANT_REAL) QT_REQUIS
	, V.UN_MEDIDA
	, SUM (CUSTO) CUSTO_MEDIO
	, (SELECT B1_CUSTD
		FROM SB1010 SB1
		WHERE SB1.D_E_L_E_T_ = ''
		AND SB1.B1_FILIAL = '  '
		AND SB1.B1_COD = V.CODIGO) AS CUSTO_REPOS_UNIT
INTO #OPS_SAFRA
FROM VA_VDADOS_OP V, #OPS
WHERE V.FILIAL = #OPS.FILIAL
AND V.OP = #OPS.OP
AND V.TIPO_MOVTO = 'C'
--AND V.GRUPO = '0400'
GROUP BY PROD_FINAL, V.DESC_PROD_FINAL, V.TIPO_PRODUTO, V.GRUPO
	, CODIGO
	, V.DESCRICAO, V.UN_MEDIDA
-- ORDER BY PROD_FINAL, V.DESC_PROD_FINAL	, CODIGO	, V.DESCRICAO
;
SELECT PROD_FINAL, DESC_PROD_FINAL, QT_PRODUZIDA, TIPO_PRODUTO
	, CODIGO, DESCRICAO
	, UN_MEDIDA
	, CASE WHEN TIPO_PRODUTO NOT IN ('AP','MO','GF') AND GRUPO = '0400'  THEN QT_REQUIS ELSE 0 END AS UVA_QT_REQUIS
	, CASE WHEN TIPO_PRODUTO NOT IN ('AP','MO','GF') AND GRUPO = '0400'  THEN CUSTO_REPOS_UNIT * QT_REQUIS ELSE 0 END AS UVA_CUSTO_REPOS
	, CASE WHEN TIPO_PRODUTO IN ('AP','MO','GF')                         THEN QT_REQUIS ELSE 0 END AS MO_QT_REQUIS
	, CASE WHEN TIPO_PRODUTO IN ('AP','MO','GF')                         THEN CUSTO_REPOS_UNIT * QT_REQUIS ELSE 0 END AS MO_CUSTO_REPOS
	, CASE WHEN TIPO_PRODUTO NOT IN ('AP','MO','GF') AND GRUPO != '0400' THEN QT_REQUIS ELSE 0 END AS OUTROS_QT_REQUIS
	, CASE WHEN TIPO_PRODUTO NOT IN ('AP','MO','GF') AND GRUPO != '0400' THEN CUSTO_REPOS_UNIT * QT_REQUIS ELSE 0 END AS OUTROS_CUSTO_REPOS
--	, CASE WHEN GRUPO = '0400' AND TIPO_PRODUTO NOT IN ('AP','MO','GF') THEN CUSTO_MEDIO ELSE 0 END AS UVA_CUSTO_MEDIO
--	, CASE WHEN GRUPO = '0400' AND TIPO_PRODUTO NOT IN ('AP','MO','GF') THEN 0 ELSE CUSTO_MEDIO END AS OUTROS_CUSTO_MEDIO
--SELECT *
FROM #OPS_SAFRA
ORDER BY PROD_FINAL, CODIGO
