--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED					
/*
-- VERIFICA SE AS TABELAS SIMULADAS POSSUEM ALGUM PRECO ABAIXO DA QUE JAH VEM SENDO USADA NA ENTRADA DA SAFRA
SELECT NOVA.ZBI_PRODUT, NOVA.ZBI_CONDUC, SB1.B1_DESC, MAX (ATUAL.ZBI_VUNIT1 - NOVA.ZBI_VUNIT1) as MAIOR_DIFERENCA_PRECO
	-- NOVA.*, B1_DESC, ATUAL.ZBI_VUNIT1, ROUND (ATUAL.ZBI_VUNIT1 - NOVA.ZBI_VUNIT1, 4) AS DIF
FROM ZBI010 NOVA
	LEFT JOIN SB1010 SB1
		ON (SB1.D_E_L_E_T_ = ''
		AND SB1.B1_FILIAL = '  '
		AND SB1.B1_COD = NOVA.ZBI_PRODUT)
	JOIN ZBI010 ATUAL
		ON (ATUAL.D_E_L_E_T_ = ''
			AND ATUAL.ZBI_FILIAL = NOVA.ZBI_FILIAL
			AND ATUAL.ZBI_CODTAB = '24A '
			AND ATUAL.ZBI_PRODUT = NOVA.ZBI_PRODUT
			AND ATUAL.ZBI_GRAU = NOVA.ZBI_GRAU
			AND ATUAL.ZBI_CONDUC = NOVA.ZBI_CONDUC
			AND ATUAL.ZBI_CLASSE = NOVA.ZBI_CLASSE
			AND ATUAL.ZBI_VUNIT1 > NOVA.ZBI_VUNIT1)
WHERE NOVA.D_E_L_E_T_ = ''
AND NOVA.ZBI_FILIAL = '  '
AND NOVA.ZBI_CODTAB IN ('24C ') --, '24D ')
GROUP BY NOVA.ZBI_PRODUT, NOVA.ZBI_CONDUC, SB1.B1_DESC
--ORDER BY ATUAL.ZBI_VUNIT1 - NOVA.ZBI_VUNIT1 DESC, NOVA.ZBI_CODTAB, NOVA.ZBI_PRODUT, NOVA.ZBI_GRAU
*/
/*
-- PREPARAR DADOS DE SAFRAS ANTERIORES					
SELECT
	PRODUTO
   ,SUM(PESO_LIQ) AS KG_RECEBIDOS
   ,ROUND(SUM(PESO_LIQ * GRAU) / SUM(PESO_LIQ), 1) AS GRAU_MEDIO
   ,ROUND(SUM(VALOR_TOTAL) / SUM (PESO_LIQ), 2) AS PRECO_MEDIO
INTO #SAFRA_2022
FROM VA_VNOTAS_SAFRA ANT
WHERE SAFRA = '2022'
AND ANT.TIPO_NF IN ('C', 'P')
GROUP BY PRODUTO
;
SELECT
	PRODUTO
   ,SUM(PESO_LIQ) AS KG_RECEBIDOS
   ,ROUND(SUM(PESO_LIQ * GRAU) / SUM(PESO_LIQ), 1) AS GRAU_MEDIO
   ,ROUND(SUM(VALOR_TOTAL) / SUM (PESO_LIQ), 2) AS PRECO_MEDIO
INTO #SAFRA_2023
FROM VA_VNOTAS_SAFRA ANT
WHERE SAFRA = '2023'
AND ANT.TIPO_NF IN ('C', 'P')
GROUP BY PRODUTO
;
SELECT
	PRODUTO
   ,SUM(PESO_LIQ) AS KG_RECEBIDOS
   ,ROUND(SUM(PESO_LIQ * GRAU) / SUM(PESO_LIQ), 1) AS GRAU_MEDIO
   ,ROUND(SUM(VALOR_TOTAL) / SUM (PESO_LIQ), 2) AS PRECO_MEDIO
INTO #SAFRA_2024
FROM VA_VNOTAS_SAFRA ANT
WHERE SAFRA = '2024'
AND ANT.TIPO_NF IN ('C', 'P')
GROUP BY PRODUTO
;					
WITH C AS (
	SELECT '9969' AS COD_PREV,  53000 AS KG_PREVISTOS				
	UNION ALL SELECT '9934' AS COD,  6000		 		
	UNION ALL SELECT '9966' AS COD,  203000	 			
	UNION ALL SELECT '9925' AS COD,  3874070	 			
	UNION ALL SELECT '9822' AS COD,  1000		 		
	UNION ALL SELECT '9948' AS COD,  1500		 		
	UNION ALL SELECT '9959' AS COD,  345600	 			
	UNION ALL SELECT '9844' AS COD,  1759100	 			
	UNION ALL SELECT '9849' AS COD,  156000	 			
	UNION ALL SELECT '9958' AS COD,  3233250	 			
	UNION ALL SELECT '9810' AS COD,  2000		 		
	UNION ALL SELECT '9933' AS COD,  1293200	 			
	UNION ALL SELECT '9847' AS COD,  1350500	 			
	UNION ALL SELECT '99917' AS COD, 1500		 		
	UNION ALL SELECT '9976' AS COD,  862500	 			
	UNION ALL SELECT '9916' AS COD,  45000	 			
	UNION ALL SELECT '9908' AS COD,  70000	 			
	UNION ALL SELECT '9922' AS COD,  131200	 			
	UNION ALL SELECT '9855' AS COD,  78000	 			
	UNION ALL SELECT '9909' AS COD,  241600	 			
	UNION ALL SELECT '9804' AS COD,  2000		 		
	UNION ALL SELECT '9906' AS COD,  368900	 			
	UNION ALL SELECT '9806' AS COD,  5000		 		
	UNION ALL SELECT '9924' AS COD,  18500	 			
	UNION ALL SELECT '9820' AS COD,  15000	 			
	UNION ALL SELECT '9903' AS COD,  131200	 			
	UNION ALL SELECT '9901' AS COD,  8630200	 			
	UNION ALL SELECT '9960' AS COD,  71500	 			
	UNION ALL SELECT '9940' AS COD,  934800	 			
	UNION ALL SELECT '9808' AS COD,  34500	 			
	UNION ALL SELECT '9926' AS COD,  49400	 			
	UNION ALL SELECT '9979' AS COD,  12000	 			
	UNION ALL SELECT '9860' AS COD,  3000		 		
	UNION ALL SELECT '9913' AS COD,  956000	 			
	UNION ALL SELECT '99910' AS COD, 50800	 			
	UNION ALL SELECT '9835' AS COD,  6000		 		
	UNION ALL SELECT '9917' AS COD,  255000	 			
	UNION ALL SELECT '99923' AS COD, 10000	 			
	UNION ALL SELECT '9911' AS COD,  849500	 			
	UNION ALL SELECT '99905' AS COD, 7000		 		
	UNION ALL SELECT '9918' AS COD,  1136700	 			
	UNION ALL SELECT '9932' AS COD,  67000	 			
	UNION ALL SELECT '9845' AS COD,  15000	 			
	UNION ALL SELECT '9904' AS COD,  1541750	 			
	UNION ALL SELECT '9831' AS COD,  3500		 		
	UNION ALL SELECT '9905' AS COD,  375050	 			
	UNION ALL SELECT '9818' AS COD,  15500	 			
	UNION ALL SELECT '9928' AS COD,  23000	 			
	UNION ALL SELECT '9920' AS COD,  13000	 			
	UNION ALL SELECT '9852' AS COD,  11000	 			
	UNION ALL SELECT '9936' AS COD,  149500	 			
	UNION ALL SELECT '9812' AS COD,  3500		 		
	UNION ALL SELECT '9923' AS COD,  124300	 			
	UNION ALL SELECT '9907' AS COD,  1000		 		
	UNION ALL SELECT '9931' AS COD,  800		 		
	UNION ALL SELECT '9939' AS COD,  211000	 			
	UNION ALL SELECT '9912' AS COD,  377000	 			
)
SELECT *
INTO #PREVISAO_AGRO
FROM C
;

-- APLICA REDUCAO NAS QUANTIDADES PREVISTAS
--SELECT #PREVISAO_AGRO.* , B1_VARUVA, B1_DESC
UPDATE #PREVISAO_AGRO SET KG_PREVISTOS = KG_PREVISTOS * CASE B1_VARUVA WHEN 'C' THEN 0.75 WHEN 'F' THEN 0.6 ELSE 1 END
FROM #PREVISAO_AGRO, SB1010 SB1
WHERE SB1.D_E_L_E_T_ = ''
AND SB1.B1_FILIAL = '  '
AND SB1.B1_COD = #PREVISAO_AGRO.COD_PREV
;
-- LISTA DE TODAS AS VARIEDADES ENVOLVIDAS (POR QUE POSSO TER PREVISAO SEM RECEBIMENTO E VICE-VERSA)
WITH C AS (
	SELECT DISTINCT PRODUTO FROM #SAFRA_2022 UNION				
	SELECT DISTINCT PRODUTO FROM #SAFRA_2023 UNION				
	SELECT DISTINCT PRODUTO FROM #SAFRA_2024 UNION				
	SELECT DISTINCT COD_PREV FROM #PREVISAO_AGRO				
)
SELECT *
INTO #VARIEDADES
FROM C
;
-- JUNTA TODAS AS VARIEDAES POSSIVEIS, COM COLUNAS REFERENTES A CADA SAFRA
SELECT #VARIEDADES.PRODUTO AS VARIEDADE --ISNULL (SAFRA_2024.PRODUTO, ISNULL (SAFRA_2023.PRODUTO, ISNULL (SAFRA_2022.PRODUTO, PREVISAO.COD_PREV))) AS VARIEDADE					
	, isnull (#SAFRA_2022.KG_RECEBIDOS, 0) AS KG_22				
	, isnull (#SAFRA_2022.GRAU_MEDIO, 0) AS GR_MEDIO_22				
	, isnull (#SAFRA_2022.PRECO_MEDIO, 0) AS PRC_MEDIO_22				
	, isnull (#SAFRA_2023.KG_RECEBIDOS, 0) AS KG_23				
	, isnull (#SAFRA_2023.GRAU_MEDIO, 0) AS GR_MEDIO_23				
	, isnull (#SAFRA_2023.PRECO_MEDIO, 0) AS PRC_MEDIO_23				
	, isnull (#SAFRA_2024.KG_RECEBIDOS, 0) AS KG_24				
	, isnull (#SAFRA_2024.GRAU_MEDIO, 0) AS GR_MEDIO_24				
	, isnull (#SAFRA_2024.PRECO_MEDIO, 0) AS PRC_MEDIO_24				
	, isnull (#PREVISAO_AGRO.KG_PREVISTOS, 0) AS KG_PREV_2024				
	, CAST (CASE WHEN #SAFRA_2024.GRAU_MEDIO IS NULL				
		THEN CASE WHEN #SAFRA_2023.GRAU_MEDIO IS NULL			
			THEN CASE WHEN #SAFRA_2022.GRAU_MEDIO IS NULL		
				THEN 15	
				ELSE #SAFRA_2022.GRAU_MEDIO	
				END	
			ELSE #SAFRA_2023.GRAU_MEDIO		
			END		
		ELSE #SAFRA_2024.GRAU_MEDIO			
		END AS DECIMAL (5, 1)			
		) AS GRAU_PARA_PRECIFICAR
	INTO #SAFRAS
from #VARIEDADES					
	LEFT JOIN #SAFRA_2024 on (#SAFRA_2024.PRODUTO = #VARIEDADES.PRODUTO)				
	LEFT JOIN #SAFRA_2023 on (#SAFRA_2023.PRODUTO = #VARIEDADES.PRODUTO)				
	LEFT JOIN #SAFRA_2022 on (#SAFRA_2022.PRODUTO = #VARIEDADES.PRODUTO)				
	LEFT JOIN #PREVISAO_AGRO ON (COD_PREV = #VARIEDADES.PRODUTO)				

;
*/

-- APLICA PRECOS PREVISTOS
drop table IF EXISTS #PREV_PAGTO;
SELECT VARIEDADE, RTRIM (SB1.B1_DESC) AS DESCRICAO
	, KG_22, GR_MEDIO_22, PRC_MEDIO_22
	, KG_23, GR_MEDIO_23, PRC_MEDIO_23
	, KG_24, GR_MEDIO_24, PRC_MEDIO_24
	, #SAFRAS.GRAU_PARA_PRECIFICAR					
	, KG_PREV_2024
	, (SELECT ZBI_VUNIT1				
		FROM ZBI010 ZBI			
		WHERE ZBI.D_E_L_E_T_ = ''			
		AND ZBI.ZBI_CODTAB = '24C '			
		AND ZBI.ZBI_FILIAL = '  '			
		AND ZBI.ZBI_PRODUT = #SAFRAS.VARIEDADE			
		and ZBI.ZBI_GRAU = REPLACE (#SAFRAS.GRAU_PARA_PRECIFICAR, ',', '.')			
		and ZBI.ZBI_CLASSE = CASE WHEN SB1.B1_VARUVA = 'C' THEN '  ' ELSE 'B' END  -- CLASSIFICACAO 'BASE'			
		AND ZBI.ZBI_CONDUC = CASE WHEN SB1.B1_VAUVAES = 'S' THEN 'E' ELSE 'L' END -- TODA A PREV. DA AGRONOMIA EH LATADA			
		) AS PRC_CONSERVADOR
	, (SELECT ZBI_VUNIT1				
		FROM ZBI010 ZBI			
		WHERE ZBI.D_E_L_E_T_ = ''			
		AND ZBI.ZBI_CODTAB = '24D '			
		AND ZBI.ZBI_FILIAL = '  '			
		AND ZBI.ZBI_PRODUT = #SAFRAS.VARIEDADE			
		and ZBI.ZBI_GRAU = REPLACE (#SAFRAS.GRAU_PARA_PRECIFICAR, ',', '.')			
		and ZBI.ZBI_CLASSE = CASE WHEN SB1.B1_VARUVA = 'C' THEN '  ' ELSE 'B' END  -- CLASSIFICACAO 'BASE'			
		AND ZBI.ZBI_CONDUC = CASE WHEN SB1.B1_VAUVAES = 'S' THEN 'E' ELSE 'L' END -- TODA A PREV. DA AGRONOMIA EH LATADA			
		) AS PRC_AGRESSIVO
	INTO #PREV_PAGTO
from #SAFRAS 
	LEFT JOIN SB1010 SB1					
	ON (SB1.D_E_L_E_T_ = ''					
	AND SB1.B1_FILIAL = '  '					
	AND SB1.B1_COD = #SAFRAS.VARIEDADE)					
ORDER BY SB1.B1_DESC					

;

SELECT
	*
   ,KG_PREV_2024 * PRC_CONSERVADOR AS TOTAL_CONSERVADOR
   ,KG_PREV_2024 * PRC_AGRESSIVO AS TOTAL_AGRESSIVO
FROM #PREV_PAGTO
ORDER BY DESCRICAO
