SELECT OPV.PRIMEIRO_MOVTO
	, OPV.ULTIMO_MOVTO
	, OPV.FILIAL, OPV.OP, MAX (SB1_PRODUCAO.B1_DESC) AS PRODUTO_FINAL
	, SUM (SD3_PRODUCAO.D3_QUANT * SB1_PRODUCAO.B1_LITROS) AS LITROS_PRODUZIDOS
	--, COUNT (*) OVER (PARTITION BY CONSUMOS.D3_FILIAL, CONSUMOS.D3_OP) AS CONTAGEM
	, SUM (CASE WHEN CONSUMOS.TIPO_CONSUMO = 'CONSUMO_UVA' THEN CONSUMOS.D3_QUANT ELSE 0 END) AS KG_UVA_CONSUMIDA
	, SUM (CASE WHEN CONSUMOS.TIPO_CONSUMO = 'CONSUMO_ACUCAR' THEN CONSUMOS.D3_QUANT * CONSUMOS.B1_PESO ELSE 0 END) AS KG_ACUCAR_CONSUMIDO
	, SUM (CASE WHEN CONSUMOS.TIPO_CONSUMO = 'CONSUMO_INSUMOS' THEN CONSUMOS.D3_QUANT * CONSUMOS.B1_PESO ELSE 0 END) AS KG_INSUMOS_CONSUMIDOS
FROM VA_VOPS_DE_VINIFICACAO OPV
	LEFT JOIN SD3010 SD3_PRODUCAO
		LEFT JOIN SB1010 SB1_PRODUCAO
			ON (SB1_PRODUCAO.D_E_L_E_T_ = ''
			AND SB1_PRODUCAO.B1_FILIAL = '  '
			AND SB1_PRODUCAO.B1_COD = SD3_PRODUCAO.D3_COD)
		ON (SD3_PRODUCAO.D_E_L_E_T_ = ''
		AND SD3_PRODUCAO.D3_FILIAL = OPV.FILIAL
		AND SD3_PRODUCAO.D3_OP = OPV.OP
		AND SD3_PRODUCAO.D3_ESTORNO = ''
		AND SD3_PRODUCAO.D3_CF LIKE 'PR%')
		LEFT JOIN (SELECT D3_FILIAL
					, D3_OP, SD3_CONSUMO.D3_COD
					, SD3_CONSUMO.D3_QUANT
					, SB1_CONSUMO.B1_DESC, SB1_CONSUMO.B1_PESO
					, CASE WHEN SD3_CONSUMO.D3_GRUPO = '0400'
						THEN 'CONSUMO_UVA'
					ELSE CASE WHEN SD3_CONSUMO.D3_TIPO = 'PS'
						THEN CASE WHEN SB1_CONSUMO.B1_DESC LIKE 'ACUCAR%'
							THEN 'CONSUMO_ACUCAR'
							ELSE 'CONSUMO_INSUMOS'
							END
					END END AS TIPO_CONSUMO
					FROM SD3010 SD3_CONSUMO
						LEFT JOIN SB1010 SB1_CONSUMO
							ON (SB1_CONSUMO.D_E_L_E_T_ = ''
							AND SB1_CONSUMO.B1_FILIAL = '  '
							AND SB1_CONSUMO.B1_COD = SD3_CONSUMO.D3_COD)
			WHERE SD3_CONSUMO.D_E_L_E_T_ = ''
			AND SD3_CONSUMO.D3_ESTORNO = ''
			AND SD3_CONSUMO.D3_CF LIKE 'RE%'
			) AS CONSUMOS
		ON (CONSUMOS.D3_FILIAL = OPV.FILIAL
		AND CONSUMOS.D3_OP = OPV.OP)
WHERE OPV.PRIMEIRO_MOVTO >= '20240101' AND OPV.ULTIMO_MOVTO <= '20241231'
GROUP BY OPV.FILIAL, OPV.OP, OPV.PRIMEIRO_MOVTO
	, OPV.ULTIMO_MOVTO
ORDER BY OPV.FILIAL, OPV.OP

-- select * from dbo.VA_FAdmOP ('03', '03', '', 'Z', '00252801001   ', '00252801001   ')
--select * from SD3010 where D3_FILIAL = '03' AND D3_OP = '00252801001   '
