WITH C AS (
SELECT  OPV.FILIAL, OPV.OP
	,OPV.PRIMEIRO_MOVTO, OPV.ULTIMO_MOVTO
	, MAX (CASE WHEN SD3.D3_CF LIKE 'PR%' THEN SD3.D3_COD ELSE '' END) AS COD_PRODUZIDO
	, SUM (CASE WHEN SD3.D3_CF LIKE 'PR%' THEN SD3.D3_QUANT * SB1.B1_LITROS ELSE 0 END) AS PRODUZIDO_LITROS
	, SUM (CASE WHEN SD3.D3_CF LIKE 'PR%' THEN SD3.D3_CUSTO1 ELSE 0 END) AS PRODUZIDO_CUSTO
	, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_GRUPO = '0400' THEN SD3.D3_QUANT ELSE 0 END) AS CONSUMO_UVA_KG
	, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_GRUPO = '0400' THEN SD3.D3_CUSTO1 ELSE 0 END) AS CONSUMO_UVA_CUSTO
	, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'PS' AND SB1.B1_DESC LIKE 'ACUCAR%' THEN SD3.D3_QUANT ELSE 0 END) AS CONSUMO_ACUCAR_KG
	, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'PS' AND SB1.B1_DESC LIKE 'ACUCAR%' THEN SD3.D3_CUSTO1 ELSE 0 END) AS CONSUMO_ACUCAR_CUSTO
	, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'PS' AND SB1.B1_DESC NOT LIKE 'ACUCAR%' THEN SD3.D3_QUANT ELSE 0 END) AS CONSUMO_INSUMOS_KG
	, SUM (CASE WHEN SD3.D3_CF LIKE 'RE%' AND SD3.D3_TIPO = 'PS' AND SB1.B1_DESC NOT LIKE 'ACUCAR%' THEN SD3.D3_CUSTO1 ELSE 0 END) AS CONSUMO_INSUMOS_CUSTO
FROM VA_VOPS_DE_VINIFICACAO OPV
	LEFT JOIN SD3010 SD3
		LEFT JOIN SB1010 SB1
			ON (SB1.D_E_L_E_T_ = ''
			AND SB1.B1_FILIAL = '  '
			AND SB1.B1_COD = SD3.D3_COD)
		ON (SD3.D_E_L_E_T_ = ''
		AND SD3.D3_FILIAL = OPV.FILIAL
		AND SD3.D3_OP = OPV.OP
		AND SD3.D3_ESTORNO = '')
--WHERE OPV.PRIMEIRO_MOVTO >= '20240101' AND OPV.ULTIMO_MOVTO <= '20241231'
GROUP BY OPV.FILIAL, OPV.OP, OPV.PRIMEIRO_MOVTO, OPV.ULTIMO_MOVTO
)
SELECT C.*, ROUND (PRODUZIDO_LITROS / CONSUMO_UVA_KG, 2) AS RENDIMENTO, B1_DESC
FROM C, SB1010 SB1
WHERE SB1.D_E_L_E_T_ = ''
			AND SB1.B1_FILIAL = '  '
			AND SB1.B1_COD = COD_PRODUZIDO
ORDER BY FILIAL, OP
