;WITH SALDOS AS (
select 'ATUAL' AS ANO_MES, B2_FILIAL AS FILIAL, B2_COD AS PRODUTO, SUM (B2_QATU) AS SALDO, 0 AS CUSTO
FROM SB2010 SB2
WHERE SB2.D_E_L_E_T_ = ''
AND SB2.B2_QATU > 0
GROUP BY SB2.B2_FILIAL, SB2.B2_COD
UNION ALL
select SUBSTRING (SB9.B9_DATA, 1, 6) AS ANO_MES, B9_FILIAL AS FILIAL, B9_COD AS PRODUTO, SUM (B9_QINI) AS SALDO, SUM (SB9.B9_VINI1) AS CUSTO
FROM SB9010 SB9
WHERE SB9.D_E_L_E_T_ = ''
AND SB9.B9_QINI > 0
AND SB9.B9_VINI1 > 0
AND B9_DATA >= '20220101'
GROUP BY SUBSTRING (SB9.B9_DATA, 1, 6), B9_FILIAL, B9_COD
)
select ANO_MES, FILIAL, SB1.B1_CODLIN AS COD_LIN_COML, ZX5_39.ZX5_39DESC AS DESC_LIN_COML
, B1_TIPO AS TIPO, SALDOS.PRODUTO, B1_DESC AS DESCRICAO, SALDO, B1_UM AS UN_MED
, SALDO * B1_LITROS AS SALDO_LITROS, CUSTO
FROM SALDOS, SB1010 SB1
	LEFT JOIN ZX5010 ZX5_39
	ON (ZX5_39.ZX5_FILIAL = '  '
	AND ZX5_39.D_E_L_E_T_ = ''
	AND ZX5_39.ZX5_TABELA = '39'
	AND ZX5_39.ZX5_39COD  = SB1.B1_CODLIN)
WHERE SB1.D_E_L_E_T_ = ''
AND SB1.B1_FILIAL = '  '
AND SB1.B1_COD = SALDOS.PRODUTO
ORDER BY ANO_MES, FILIAL, PRODUTO
