--SELECT * FROM ZX5010 WHERE ZX5_TABELA = '54' AND D_E_L_E_T_ = ''
select CHAVE, AVG (SEGUNDOS) AS MEDIA_SEGUNDOS, COUNT (*) AS QT_EXECUCOES
FROM VA_PERFMON
WHERE DTHR >= '20230509 00:48'
AND (CHAVE LIKE 'Prep_env%' or CHAVE LIKE 'Gravar_evento_%')
GROUP BY CHAVE
