
SELECT TRB_TES
	,(SELECT TRB_NIVEL
			FROM TRB01SP PAR
			WHERE PAR.D_E_L_E_T_ = '' AND PAR.TRB_FILIAL = TRB01SP.TRB_FILIAL
			AND PAR.TRB_ALIAS = 'SD1'
			AND PAR.TRB_TES = '140'
			AND PAR.TRB_ORDEM = '300'
			AND PAR.TRB_SEQ = TRB01SP.TRB_SEQ
			AND PAR.TRB_COD = TRB01SP.TRB_COD
			AND PAR.TRB_DOC = TRB01SP.TRB_DOC)
	,*
	FROM TRB01SP
--begin tran; update TRB01SP SET TRB_NIVEL = '99A'
WHERE D_E_L_E_T_ = ''
AND TRB_ALIAS = 'SD3' AND TRB_CF = 'RE5' AND TRB_ORDEM = '300'
AND EXISTS (SELECT *
			FROM TRB01SP PAR
			WHERE PAR.D_E_L_E_T_ = '' AND PAR.TRB_FILIAL = TRB01SP.TRB_FILIAL
			AND PAR.TRB_ALIAS = 'SD1'
			AND PAR.TRB_TES = '140'
			AND PAR.TRB_ORDEM = '300'
			AND PAR.TRB_SEQ = TRB01SP.TRB_SEQ
			AND PAR.TRB_COD = TRB01SP.TRB_COD
			AND PAR.TRB_DOC = TRB01SP.TRB_DOC)


