SELECT
	CCAI.CCAssocIEGrpFamCod AS GRP_FAMILIAR_COD
   ,RTRIM(CCAGF.CCAssociadoGrpFam) AS GRP_FAMILIAR_DESCRICAO
   ,V.SAFRA
   ,V.ASSOCIADO
   ,V.NOME_ASSOC
   ,V.PRODUTO
   ,V.DESCRICAO
   ,SUM(V.PESO_LIQ) AS PESO_LIQ
FROM VA_VNOTAS_SAFRA V
LEFT JOIN LKSRV_NAWEB.naweb.dbo.CCAssociadoInscricoes CCAI
LEFT JOIN LKSRV_NAWEB.naweb.dbo.CCAssociadoGrpFam CCAGF
	ON (CCAGF.CCAssociadoGrpFamCod = CCAssocIEGrpFamCod)
	ON (CCAI.CCAssociadoCod = V.ASSOCIADO
			AND CCAI.CCAssociadoLoja = V.LOJA_ASSOC)
WHERE V.SAFRA >= '2020'
AND V.TIPO_NF IN ('C', 'P')
GROUP BY CCAI.CCAssocIEGrpFamCod
		,RTRIM(CCAGF.CCAssociadoGrpFam)
		,V.SAFRA
		,V.ASSOCIADO
		,V.NOME_ASSOC
		,V.PRODUTO
		,V.DESCRICAO