-- Lista de privilegios do configurador
SELECT R.RL__ID AS PRIV_ID, R.RL__CODIGO AS PRIV_CODIGO, R.RL__DESCRI AS PRIV_DESCRICAO
	, T.RL__ROTINA AS ROTINA, T.RL__DESROT AS DESC_ROTINA, T.RL__ACESSO + '-' + CASE T.RL__ACESSO WHEN '1' THEN 'Permitido' WHEN '2' THEN 'Nao permitido' WHEN '3' THEN 'Bloqueado' END AS ACESSO_ROTINA
	, F.RL__MENUOPER AS MENUOPER, F.RL__MENUDEF AS MENUDEF, F.RL__DESMDEF AS MENUDESC, F.RL__ACESSO + '-' + CASE F.RL__ACESSO WHEN '1' THEN 'Permitido' WHEN '2' THEN 'Nao permitido' WHEN '3' THEN 'Bloqueado' END AS MENU_ACESSO
FROM SYS_RULES R
, SYS_RULES_TRANSACT T
, SYS_RULES_FEATURES F 
WHERE R.D_E_L_E_T_ = ''
AND T.D_E_L_E_T_ = ''
AND T.RL__ID = R.RL__ID
AND F.D_E_L_E_T_ = ''
AND F.RL__ID = R.RL__ID
AND F.RL__ROTINA = T.RL__ROTINA
--and T.RL__ROTINA = 'CTBA015'
order by F.RL__ID, F.RL__ROTINA


-- Lista de privilegios e grupos de usuarios associados a eles
SELECT PRIV.RL__ID, PRIV.RL__CODIGO, PRIV.RL__DESCRI
	,GRP.GR__ID, GRP.GR__CODIGO, GRP.GR__NOME
FROM SYS_RULES PRIV
	INNER JOIN SYS_RULES_GRP_RULES PRIVGRP
		LEFT JOIN SYS_GRP_GROUP GRP
		ON (GRP.D_E_L_E_T_ = '' AND GRP.GR__MSBLQL != '1' AND GRP.GR__ID = PRIVGRP.GROUP_ID)
	ON (PRIVGRP.D_E_L_E_T_ = '' AND PRIVGRP.GR__RL_ID = PRIV.RL__ID)
WHERE PRIV.RL__ID NOT IN ('000002')
ORDER BY PRIVGRP.GR__RL_ID, GRP.GR__ID

-- Lista de privilegios e usuarios (nao grupos) associados a eles
SELECT PRIV.RL__ID, PRIV.RL__CODIGO, PRIV.RL__DESCRI, PRIVUSR.USER_ID, USR.USR_CODIGO, USR.USR_NOME
FROM SYS_RULES PRIV
	INNER JOIN SYS_RULES_USR_RULES PRIVUSR
		LEFT JOIN SYS_USR USR
		ON (USR.D_E_L_E_T_ = '' AND USR.USR_ID = PRIVUSR.USER_ID)
	ON (PRIVUSR.D_E_L_E_T_ = '' AND PRIVUSR.USR_RL_ID = PRIV.RL__ID)
--WHERE PRIV.RL__ID IN ('000004', '000005')
ORDER BY PRIV.RL__ID, PRIVUSR.USER_ID
