SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Descricao: Verifica se determinada pessoa deve ter seu acesso liberado neste momento. Retorna tambem dados de horarios para conferencia.
-- Autor....: Robert Koch
-- Data.....: 19/10/2020
--
-- Historico de alteracoes:
-- 21/09/2021 - Robert - Iniciada alteracao para verificar uma semana cheia, para posterior uso no A.D.
-- 09/11/2021 - Robert - Iniciada leitura de programacoes de horarios e escalas.
--

ALTER FUNCTION [dbo].[VA_FVERIFICAHORARIO2]
-- PARAMETROS DE CHAMADA
(
	@PESSOA AS INT
	,@DIASOLICITADO AS DATE
)

-- RETORNA TABELA TEMPORARIA
returns @RET TABLE (
	 DIASEMANA INT
	,DIA        DATETIME
	,H00 VARCHAR (1) DEFAULT '' NOT NULL
	,H01 VARCHAR (1) DEFAULT '' NOT NULL
	,H02 VARCHAR (1) DEFAULT '' NOT NULL
	,H03 VARCHAR (1) DEFAULT '' NOT NULL
	,H04 VARCHAR (1) DEFAULT '' NOT NULL
	,H05 VARCHAR (1) DEFAULT '' NOT NULL
	,H06 VARCHAR (1) DEFAULT '' NOT NULL
	,H07 VARCHAR (1) DEFAULT '' NOT NULL
	,H08 VARCHAR (1) DEFAULT '' NOT NULL
	,H09 VARCHAR (1) DEFAULT '' NOT NULL
	,H10 VARCHAR (1) DEFAULT '' NOT NULL
	,H11 VARCHAR (1) DEFAULT '' NOT NULL
	,H12 VARCHAR (1) DEFAULT '' NOT NULL
	,H13 VARCHAR (1) DEFAULT '' NOT NULL
	,H14 VARCHAR (1) DEFAULT '' NOT NULL
	,H15 VARCHAR (1) DEFAULT '' NOT NULL
	,H16 VARCHAR (1) DEFAULT '' NOT NULL
	,H17 VARCHAR (1) DEFAULT '' NOT NULL
	,H18 VARCHAR (1) DEFAULT '' NOT NULL
	,H19 VARCHAR (1) DEFAULT '' NOT NULL
	,H20 VARCHAR (1) DEFAULT '' NOT NULL
	,H21 VARCHAR (1) DEFAULT '' NOT NULL
	,H22 VARCHAR (1) DEFAULT '' NOT NULL
	,H23 VARCHAR (1) DEFAULT '' NOT NULL
	)

AS
BEGIN
	DECLARE @CONTINUA BIT = 1;
	DECLARE @OP05 VARCHAR (1) = ''
	DECLARE @EM_FERIAS VARCHAR (1) = ''
	DECLARE @CONTRATO INT = 0
	DECLARE @SITUACAOFOLHA VARCHAR (1) = ''
	DECLARE @ESCALACONTRATO     VARCHAR (4) = ''
/*
	DECLARE @DESCRICAOHORARIO   VARCHAR (40) = ''
	DECLARE @HORAINI VARCHAR (5) = ''
	DECLARE @HORAFIM VARCHAR (5) = ''
	DECLARE @ACAO VARCHAR (1) = ''
	DECLARE @OBS VARCHAR (100) = ''
	DECLARE @DIASEMANA INT = 0
	DECLARE @MINUTOSTOLERANCIAANTES INT = 20;
	DECLARE @MINUTOSTOLERANCIADEPOIS INT = 20;
	DECLARE @INICIOLIBERACAO DATETIME;
	DECLARE @FIMLIBERACAO DATETIME;
	DECLARE @DTHRAUX DATETIME;
	DECLARE @DTHRSOLICITADA_INI DATETIME;
	DECLARE @DTHRSOLICITADA_FIM DATETIME;
*/
	-- INICIALIZA TABELA A SER RETORNADA COM OS 7 DIAS DA SEMANA ATUAL.
	-- ORIGINAL --> DECLARE @DOMINGO DATE = dateadd(day, 1-datepart(dw, getdate()), CONVERT(date,getdate()))  -- https://stackoverflow.com/questions/23051197/how-to-get-data-of-current-week-only-in-sql-server/32226598
	DECLARE @DOMINGO DATE = dateadd(day, 1-datepart(dw, @DIASOLICITADO), CONVERT(date, @DIASOLICITADO))
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (1, @DOMINGO);
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (2, DATEADD (DAY, 1, @DOMINGO));
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (3, DATEADD (DAY, 2, @DOMINGO));
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (4, DATEADD (DAY, 3, @DOMINGO));
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (5, DATEADD (DAY, 4, @DOMINGO));
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (6, DATEADD (DAY, 5, @DOMINGO));
	INSERT INTO @RET (DIASEMANA, DIA) VALUES (7, DATEADD (DAY, 6, @DOMINGO));


	-- BUSCA DADOS PRINCIPAIS DA PESSOA
	SELECT TOP 1 @OP05           = ISNULL (OP05, 1)  -- TRATA NULL COMO SE FOSSE 1.
				,@EM_FERIAS      = ISNULL (EM_FERIAS, '')
				,@CONTRATO       = ISNULL (CONTRATO, '')
				,@ESCALACONTRATO = ISNULL (ESCALA_CONTRATO, '')
				,@SITUACAOFOLHA  = ISNULL (SITUACAO, '')
	FROM VA_VFUNCIONARIOS
	WHERE PESSOA = @PESSOA


	-- VERIFICA A SITUACAO DO CAMPO 'OPC05', QUE EH ONDE O PESSOAL DO RH PODE INFORMAR COMO O FUNCIONARIO DEVE SER TRATADO
	IF (@OP05 = 3)  --Pessoa marcada como SEMPRE LIBERAR
	BEGIN
		UPDATE @RET SET H00 = 'L',H01 = 'L',H02 = 'L',H03 = 'L',H04 = 'L',H05 = 'L',H06 = 'L',H07 = 'L',H08 = 'L',H09 = 'L',H10 = 'L',H11 = 'L',H12 = 'L',H13 = 'L',H14 = 'L',H15 = 'L',H16 = 'L',H17 = 'L',H18 = 'L',H19 = 'L',H20 = 'L',H21 = 'L',H22 = 'L',H23 = 'L'
		SET @CONTINUA = 0;
	END
	
	IF (@CONTINUA = 1)
	BEGIN
		IF (@EM_FERIAS = 'S' OR @SITUACAOFOLHA IN ('2', '3','4'))  -- PESSOA AFASTADA OU DEMITIDA
		BEGIN
			-- NAO PRECISO FAZER NADA, POIS A TABELA DE RETORNO EH INICIALIZADA VAZIA.
			SET @CONTINUA = 0;
		END
	END

	-- confirmar, ainda, onde eh que preciso verificar se tem ocorrencias como atestado.

	-- VERIFICA SE TEM PROGRAMACAO DE HORA EXTRA
	IF (@CONTINUA = 1)
	BEGIN
		-- PRECISO VERIFICAR EM TODOS OS DIAS DA SEMANA A SER RETORNADA.
		UPDATE @RET SET H00 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 00:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 00:00' AS DATETIME))
		UPDATE @RET SET H01 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 01:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 01:00' AS DATETIME))
		UPDATE @RET SET H02 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 02:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 02:00' AS DATETIME))
		UPDATE @RET SET H03 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 03:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 03:00' AS DATETIME))
		UPDATE @RET SET H04 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 04:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 04:00' AS DATETIME))
		UPDATE @RET SET H05 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 05:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 05:00' AS DATETIME))
		UPDATE @RET SET H06 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 06:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 06:00' AS DATETIME))
		UPDATE @RET SET H07 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 07:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 07:00' AS DATETIME))
		UPDATE @RET SET H08 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 08:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 08:00' AS DATETIME))
		UPDATE @RET SET H09 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 09:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 09:00' AS DATETIME))
		UPDATE @RET SET H10 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 10:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 10:00' AS DATETIME))
		UPDATE @RET SET H11 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 11:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 11:00' AS DATETIME))
		UPDATE @RET SET H12 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 12:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 12:00' AS DATETIME))
		UPDATE @RET SET H13 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 13:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 13:00' AS DATETIME))
		UPDATE @RET SET H14 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 14:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 14:00' AS DATETIME))
		UPDATE @RET SET H15 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 15:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 15:00' AS DATETIME))
		UPDATE @RET SET H16 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 16:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 16:00' AS DATETIME))
		UPDATE @RET SET H17 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 17:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 17:00' AS DATETIME))
		UPDATE @RET SET H18 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 18:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 18:00' AS DATETIME))
		UPDATE @RET SET H19 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 19:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 19:00' AS DATETIME))
		UPDATE @RET SET H20 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 20:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 20:00' AS DATETIME))
		UPDATE @RET SET H21 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 21:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 21:00' AS DATETIME))
		UPDATE @RET SET H22 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 22:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 22:00' AS DATETIME))
		UPDATE @RET SET H23 = 'E' WHERE EXISTS (SELECT * FROM RHAUTHORASEXTRAS HE WHERE CONTRATO = @CONTRATO AND CAST (FORMAT (HE.DATAINICIO, 'yyyy-MM-dd') + ' ' + SUBSTRING (HE.HORADE, 1, 2) + ':00' AS DATETIME) <= CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 23:00' AS DATETIME) AND CAST (FORMAT (HE.DATATERMINO, 'yyyy-MM-dd') + ' ' + HE.HORAATE AS DATETIME) > CAST (FORMAT (DIA, 'yyyy-MM-dd') + ' 23:00' AS DATETIME))
	END
	
	-- VERIFICA SE TEM PROGRAMACAO DE HORARIO. SE NAO TIVER, VERIFICA SE TEM PROGRAMACAO DE ESCALA.
	IF (@CONTINUA = 1)
	BEGIN
		DECLARE @CODHORARIOPROGRAMADO1 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (@DOMINGO, 'yyyy-MM-dd')), '')
		DECLARE @CODHORARIOPROGRAMADO2 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (DATEADD (DAY, 1, @DOMINGO), 'yyyy-MM-dd')), '')
		DECLARE @CODHORARIOPROGRAMADO3 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (DATEADD (DAY, 2, @DOMINGO), 'yyyy-MM-dd')), '')
		DECLARE @CODHORARIOPROGRAMADO4 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (DATEADD (DAY, 3, @DOMINGO), 'yyyy-MM-dd')), '')
		DECLARE @CODHORARIOPROGRAMADO5 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (DATEADD (DAY, 4, @DOMINGO), 'yyyy-MM-dd')), '')
		DECLARE @CODHORARIOPROGRAMADO6 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (DATEADD (DAY, 5, @DOMINGO), 'yyyy-MM-dd')), '')
		DECLARE @CODHORARIOPROGRAMADO7 VARCHAR (4) = ISNULL ((SELECT HORARIO FROM RHPROGRAMACAOHORARIO WHERE CONTRATO = @CONTRATO AND FORMAT (DATAHORARIO, 'yyyy-MM-dd') = FORMAT (DATEADD (DAY, 6, @DOMINGO), 'yyyy-MM-dd')), '')

		-- INICIALMENTE VALE O HORARIO PROGRAMADO
		DECLARE @CODHORARIOACONSIDERAR1 VARCHAR (4) = @CODHORARIOPROGRAMADO1
		DECLARE @CODHORARIOACONSIDERAR2 VARCHAR (4) = @CODHORARIOPROGRAMADO2
		DECLARE @CODHORARIOACONSIDERAR3 VARCHAR (4) = @CODHORARIOPROGRAMADO3
		DECLARE @CODHORARIOACONSIDERAR4 VARCHAR (4) = @CODHORARIOPROGRAMADO4
		DECLARE @CODHORARIOACONSIDERAR5 VARCHAR (4) = @CODHORARIOPROGRAMADO5
		DECLARE @CODHORARIOACONSIDERAR6 VARCHAR (4) = @CODHORARIOPROGRAMADO6
		DECLARE @CODHORARIOACONSIDERAR7 VARCHAR (4) = @CODHORARIOPROGRAMADO7

--		DECLARE @CODHORARIODIASEMANA   VARCHAR (4) = ''

		-- PARA CADA DIA DA SEMANA, SE NAO TEM PROGRAMACAO DE HORARIO, BUSCA A ESCALA (QUE, SE NAO TIVER PROGRAMACAO, VALE A DO CONTRATO).
		-- CADA ESCALA SE FAZ REFERENCIA A UM HORARIO NA TABELA RHESCALASSEMANAIS
		IF (@CODHORARIOPROGRAMADO1 = '')  -- DOMINGO
		BEGIN
			DECLARE @ESCALAPROGRAMADA1 VARCHAR (4) = (SELECT ESCALA FROM RHPROGRAMACAOESCALAS WHERE CONTRATO = @CONTRATO AND FORMAT (DATAINICIO, 'yyyy-MM-dd') <= FORMAT (@DOMINGO, 'yyyy-MM-dd') AND FORMAT (DATATERMINO, 'yyyy-MM-dd') >= FORMAT (@DOMINGO, 'yyyy-MM-dd'))
			DECLARE @ESCALAACONSIDERAR1 VARCHAR (4) = ISNULL (@ESCALAPROGRAMADA1, @ESCALACONTRATO)
			SET @CODHORARIOACONSIDERAR1 = (SELECT HORARIO FROM RHESCALASSEMANAIS WHERE ESCALA = @ESCALAACONSIDERAR1 AND DIASEMANA = 7)  -- O METADADOS CONSIDERA SEGUNDA=1, TERCA=2, ..., DOMINGO=7
		END

		-- BUSCA HORARIOS DA PRIMEIRA E ULTIMA MARCACOES DE PONTO ESPERADAS PARA O HORARIO DE CADA DIA.
		DECLARE @PRIMEIRAMARCACAOESPERADA1 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR1 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @PRIMEIRAMARCACAOESPERADA2 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR2 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @PRIMEIRAMARCACAOESPERADA3 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR3 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @PRIMEIRAMARCACAOESPERADA4 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR4 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @PRIMEIRAMARCACAOESPERADA5 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR5 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @PRIMEIRAMARCACAOESPERADA6 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR6 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @PRIMEIRAMARCACAOESPERADA7 VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR7 AND CLASSEMARCACAO = '01'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA1   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR1 AND CLASSEMARCACAO = '99'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA2   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR2 AND CLASSEMARCACAO = '99'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA3   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR3 AND CLASSEMARCACAO = '99'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA4   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR4 AND CLASSEMARCACAO = '99'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA5   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR5 AND CLASSEMARCACAO = '99'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA6   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR6 AND CLASSEMARCACAO = '99'), '00:00')
		DECLARE @ULTIMAMARCACAOESPERADA7   VARCHAR (5) = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR7 AND CLASSEMARCACAO = '99'), '00:00')

		-- TENDO OS HORARIOS ESPERADOS DE MARCACOES, POSSO POPULAR A TABELA DE RETORNO.
		UPDATE @RET SET H00 = 'N' WHERE DIASEMANA = 1 AND @PRIMEIRAMARCACAOESPERADA1 LIKE '00%'
	END
/*
-- TESTES COM HORAS EXTRAS
DECLARE @PESSOA INT = 1002193; DECLARE @CTR INT = 2193; DECLARE @DT1 DATE = cast ('20201103' AS DATE); DECLARE @DT2 DATE = @DT1  -- CLAUDIA DIA 03/11/2020 17:18 AS 20:00
DECLARE @PESSOA INT = 1001868; DECLARE @CTR INT = 1868; DECLARE @DT1 DATE = cast ('20210123' AS DATE); DECLARE @DT2 DATE = DATEADD (DAY, 1, @DT1) -- 16:00 AS 02:12
DECLARE @PESSOA INT = 1001868; DECLARE @CTR INT = 1868; DECLARE @DT1 DATE = cast ('20210213' AS DATE); DECLARE @DT2 DATE = DATEADD (DAY, 1, @DT1) -- 20:30 AS 06:00
DECLARE @PESSOA INT = 1002020; DECLARE @CTR INT = 2383; DECLARE @DT1 DATE = cast ('20211014' AS DATE); DECLARE @DT2 DATE = DATEADD (DAY, 1, @DT1) -- 05:30 AS 07:30 DO DIA SEGUINTE!
select * from VA_FVERIFICAHORARIO2 (@PESSOA, @DT1)
select * from VA_FVERIFICAHORARIO2 (@PESSOA, @DT2)
SELECT TOP 10 CONTRATO, DATAINICIO, HORADE, DATATERMINO, HORAATE, * FROM RHAUTHORASEXTRAS WHERE CONTRATO = @CTR AND DATAINICIO BETWEEN @DT1 AND @DT2

-- TESTES COM PROGRAMACAO DE HORARIOS
DECLARE @PESSOA INT = 1001632; DECLARE @CTR INT = 1632; DECLARE @DT1 DATE = cast ('20210405' AS DATE); DECLARE @DT2 DATE = DATEADD (DAY, 1, @DT1) -- ROBSON SILVA 4A.FEIRA

SELECT TOP 100 CONTRATO, DATAINICIO, HORADE, DATATERMINO, HORAATE, * FROM RHAUTHORASEXTRAS WHERE DATAINICIO != DATATERMINO AND DATAINICIO >= '20210101'
SELECT TOP 100 * FROM RHAUTHORASEXTRAS WHERE HORADE > HORAATE AND DATAINICIO >= '20210101' AND SUBSTRING (HORAATE, 4, 2) != '00'
SELECT * FROM VA_VFUNCIONARIOS WHERE CONTRATO = 1632

SELECT * FROM RHPROGRAMACAOHORARIO WHERE DATAHORA >= '20210101' AND CONTRATO = 1632 AND DATAHORARIO = '20201230'
SELECT * FROM RHESCALASSEMANAIS WHERE ESCALA = '0164' AND DIASEMANA = 3
SELECT HORAMARCACAO, * FROM RHHORARIOSMARCACOES WHERE HORARIO = '0165' --AND CLASSEMARCACAO = '01'
*/
/*
	-- SE CHEGOU ATEH AQUI SEM DEFINICAO DE BLOQUEIO, PRECISA VERIFICAR HORARIOS DO CODIGO DE HORARIO A CONSIDERAR.
	IF (@ACAO = '' AND @CODHORARIOACONSIDERAR IS NULL)
	BEGIN
		SET @OBS += 'Sem definicao de horario para o ' + CAST (@DIASEMANA AS VARCHAR (1)) + 'o. dia da semana.'
		SET @ACAO = 'B'
	END

	IF (@ACAO = '')
	BEGIN
		-- BUSCA HORARIOS DA PRIMEIRA E ULTIMA MARCACOES DE PONTO ESPERADAS PARA ESSE HORARIO.
		SET @PRIMEIRAMARCACAOESPERADA = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR AND CLASSEMARCACAO = '01'), '00:00')
		SET @ULTIMAMARCACAOESPERADA = ISNULL ((SELECT HORAMARCACAO FROM RHHORARIOSMARCACOES WHERE HORARIO = @CODHORARIOACONSIDERAR AND CLASSEMARCACAO = '99'), '00:00')
--		print 'marcacoes esperadas: ' + cast (@PRIMEIRAMARCACAOESPERADA as varchar (max)) + ' e ' + cast (@ULTIMAMARCACAOESPERADA as varchar (max))

		-- APLICA TOLERANCIA AOS LIMITES DE HORARIO.
		-- TRANSFORMA EM DATETIME PARA PODER APLICAR FUNCOES DE CALCULOS COM DATAS DO SQL.
		SET @DTHRAUX = CAST (FORMAT (@DTHRSOLICITADA, 'yyyyMMdd') + ' ' + @PRIMEIRAMARCACAOESPERADA AS DATETIME)
		SET @INICIOLIBERACAO = DATEADD (MINUTE, @MINUTOSTOLERANCIAANTES * -1, @DTHRAUX)

		SET @DTHRAUX = CAST (FORMAT (@DTHRSOLICITADA, 'yyyyMMdd') + ' ' + @ULTIMAMARCACAOESPERADA AS DATETIME)
		SET @FIMLIBERACAO = DATEADD (MINUTE, @MINUTOSTOLERANCIADEPOIS, @DTHRAUX)

		-- SE DATA+HORA DE FIM MENOR QUE DATA+HORA DE INICIO, EH POR QUE TRATA-SE DE HORARIO NOTURNO (PASSA PELA MEIA NOITE)
		IF (@FIMLIBERACAO < @INICIOLIBERACAO)
		BEGIN
			--PRINT ('VIRA NOITE')
			IF (DATEPART (HOUR, @DTHRSOLICITADA) <= DATEPART (HOUR, @FIMLIBERACAO))
			BEGIN
				--PRINT 'MUDANDO INICIO LIBERACAO PARA ONTEM'
				SET @INICIOLIBERACAO = DATEADD (DAY, -1, @INICIOLIBERACAO)
			END
			ELSE
			BEGIN
				--PRINT 'MUDANDO FIM LIBERACAO PARA AMANHA'
				SET @FIMLIBERACAO = DATEADD (DAY, 1, @FIMLIBERACAO)
			END
		END
--		print 'inicio e fim liberacao: ' + cast (@INICIOLIBERACAO as varchar (max)) + ' e ' + cast (@FIMLIBERACAO as varchar (max))

		IF (@DTHRSOLICITADA >= @INICIOLIBERACAO AND @DTHRSOLICITADA <= @FIMLIBERACAO)
		BEGIN
			SET @OBS  = 'Dentro do horario normal'
			SET @ACAO = 'L'
		END
		ELSE
		BEGIN
			SET @OBS  = 'Fora do horario normal'
			SET @ACAO = 'B'
		END
	END

	INSERT INTO @RET (ACAO, OBSERVACAO, ESCALA, HORARIO, HORAINI, HORAFIM, INILIBERACAO, FIMLIBERACAO)
	VALUES (@ACAO, @OBS, @ESCALAACONSIDERAR, @CODHORARIOACONSIDERAR, @HORAINI, @HORAFIM, @INICIOLIBERACAO, @FIMLIBERACAO)
*/
RETURN
END
GO
