USE [SIRH]
GO

/****** Object:  View [dbo].[VA_VTITULOS_CPAGAR2]    Script Date: 23/10/2023 09:21:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







-- Cooperativa Agroindustrial Nova Alianca Ltda
-- View para buscar dados de titulos a serem importados do Metadados pera o Protheus (titulos a pagar).
-- Autor: Robert Koch (com base em query do programa MetaFin.prw)
-- Data:  16/12/2020
--
-- Historico de alteracoes:
-- 09/08/2021 - Robert - Passa a buscar qualquer filial, inclusive NULL, para compatibilidade com query original do programa MetaFin.prw (GLPI 10667)
--                     - Renomeadas algumas colunas e formatadas datas para yyyyMMdd (GLPI 10667)
-- 09/03/2023 - Robert - Passa a buscar IRF por filial, da mesma forma que o PIS
-- 17/04/2023 - Robert - Saparadas colunas DarfIrfMes e DarfIrfFut
--

ALTER VIEW [dbo].[VA_VTITULOS_CPAGAR2]
AS

WITH CTE
AS
(SELECT
	C.EMPRESA
	,C.DATAINCLUSAO
	,CASE C.TIPOITEMCONTAPAGAR
			WHEN '04' THEN SUBSTRING(DARF_IRF_MES.UNIDADE, 3, 2)  -- Tipo 04 = DARF IRF s/salarios: busca detalhamento em tabela especifica.
			WHEN '05' THEN SUBSTRING(DARF_PIS.UNIDADE, 3, 2)  -- Tipo 05 = DARF PIS: busca detalhamento em tabela especifica.
			WHEN '22' THEN SUBSTRING(DEP.ESTABELECIMENTO, 3, 2)  -- Tipo 22 = remessa p/ banco: busca detalhamento em tabela especifica.
			ELSE SUBSTRING(C.ESTABELECIMENTO, 3, 2)
		END AS FILIAL
	--,CASE WHEN C.TIPOITEMCONTAPAGAR = '04' THEN SUBSTRING(DARF_IRF_MES.UNIDADE, 3, 2) END AS FIL_IRFMES
	--,CASE WHEN C.TIPOITEMCONTAPAGAR = '04' THEN SUBSTRING(DARF_IRF_FUT.UNIDADE, 3, 2) END AS FIL_IRFFUT
	   ,C.NROSEQUENCIAL
	   ,ISNULL (C.NROREMESSA, '') AS NROREMESSA
	   ,FORMAT (C.DATAINCLUSAO, 'yyyyMMdd') AS EMISSAO
	   ,FORMAT (C.DATAVENCIMENTO, 'yyyyMMdd') AS VENCTO
	   ,CASE C.TIPOITEMCONTAPAGAR
			WHEN '04' THEN DARF_IRF_MES.VALOR
			WHEN '05' THEN DARF_PIS.VALOR
			WHEN '22' THEN DEP.VALOR
			ELSE C.VALOR
		END AS VALOR
		,DARF_IRF_MES.VALOR AS DarfIrfMes
		,DARF_IRF_FUT.VALOR AS DarfIrfFut
		,DARF_PIS.VALOR AS VALOR_DARF_PIS
		,DEP.VALOR AS VALOR_DEPOSITO
	   ,SUBSTRING(C.DESCRICAO20, 1, 6) AS FORNECE
	   ,RTRIM(C.DESCRICAO250) +
		CASE
			WHEN C.TIPOITEMCONTAPAGAR = '22' THEN ' (Rem.' + CAST(C.NROREMESSA AS VARCHAR) + ')'
			ELSE ''
		END AS HIST
	   ,CASE C.TIPOITEMCONTAPAGAR
			WHEN '22' THEN RTRIM(DEP.NUMERODOCUMENTO)  -- Tipo 22 = remessa p/ banco: busca detalhamento em tabela especifica.
			ELSE RTRIM(C.NUMERODOCUMENTO)
		END AS NATUREZA
	   ,C.TIPOITEMCONTAPAGAR AS TPITEMCP
	   ,CASE C.TIPOITEMCONTAPAGAR
			WHEN '01' THEN 'GPS EMPRESA MENSAL'
			WHEN '04' THEN 'DARF IRF S/ SALARIOS'
			WHEN '05' THEN 'DARF PIS'
			WHEN '09' THEN 'CONTRATO'
			WHEN '10' THEN 'DARF IRF S/ AUTONOMOS'
			WHEN '13' THEN 'GPS DIFERENCA DISSIDIO'
			WHEN '16' THEN 'GFIP (FGTS 115)'
			WHEN '19' THEN 'GFIP (FGTS 650)'
			WHEN '22' THEN 'REMESSA P/BANCO'
			WHEN '26' THEN 'PENSIONISTAS'
			WHEN '40' THEN 'FOLHA AVULSA/RPA'
			WHEN '41' THEN 'FERIAS'
			WHEN '44' THEN 'RESCISAO PRINCIPAL'
			WHEN '45' THEN 'RESCISAO COMPLEMENTAR'
			WHEN '99' THEN 'OUTROS'
			ELSE ''
		END AS DESCR_TPITCP
	   ,C.STATUSREGISTRO AS STATUSREG
	   ,CASE C.STATUSREGISTRO
			WHEN '01' THEN 'INCLUIDO (AINDA NAO LIBERADO) NO METADADOS'
			WHEN '02' THEN 'LIBERADO (METADADOS) PARA O PROTHEUS IMPORTAR'
			WHEN '03' THEN 'ACEITO PELO PROTHEUS'
			WHEN '05' THEN 'EXCLUIDO NO PROTHEUS'
			WHEN '06' THEN 'EXCLUSAO NEGADA PELO PROTHEUS'
			WHEN '07' THEN 'EXCLUIDO NO METADADOS (AGUARDA EXCLUSAO PELO PROTHEUS)'
			WHEN '08' THEN 'REJEITADO PELO PROTHEUS'
			WHEN '10' THEN 'PROVISIONADO'
		END AS DESCR_STATUS
	FROM RHCONTASPAGARHIST C

	-- Busca detalhamento de remessa para bancos.
	LEFT JOIN (SELECT
			EMPRESA
		   ,BANCO
		   ,NROREMESSA
		   ,ESTABELECIMENTO
		   ,NUMERODOCUMENTO
		   ,SUM(VALOR) AS VALOR
		FROM RHDEPOSITOSANALITICO
		WHERE EMPRESA = '00' + '01'
		GROUP BY EMPRESA
				,BANCO
				,NROREMESSA
				,ESTABELECIMENTO
				,NUMERODOCUMENTO) AS DEP
		ON (DEP.EMPRESA = C.EMPRESA
		AND DEP.BANCO = C.BANCO
		AND DEP.NROREMESSA = C.NROREMESSA
		AND C.TIPOITEMCONTAPAGAR = '22')

	-- Busca detalhamento de DARF para pagamento de PIS.
	-- Quando o RH gera os titulos de PIS antes do final do mes, a query abaixo nao os encontra (dataemissao > datainclusao). A solucao
	-- atual eh incluir manualmente no financeiro. Outra possibilidade seria desvincular os titulos de PIS desta rotina automatica
	-- e fazer a geracao atraves de um programa com parametrizacao manual do usuario, assim poderia gerar em qualquer data.
	LEFT JOIN (SELECT
			D.EMPRESA
		   ,D.UNIDADE
		   ,D.DATAEMISSAO
		   ,SUM (D.LIQUIDOCOMPETENCIA) AS VALOR
		FROM RHDARFANALITICO D
		WHERE D.ESTABELECIMENTO = '00' + '01'
		AND D.TIPODARF = '3'  -- 3=PIS
		AND D.DATAEMISSAO = (SELECT	MAX (D2.DATAEMISSAO)
			FROM RHDARFANALITICO D2
			WHERE D2.ESTABELECIMENTO = D.ESTABELECIMENTO
			AND D2.TIPODARF = D.TIPODARF)
		GROUP BY D.EMPRESA
				,D.UNIDADE
				,D.DATAEMISSAO) AS DARF_PIS
		ON (DARF_PIS.EMPRESA = C.EMPRESA
		AND DARF_PIS.DATAEMISSAO < C.DATAINCLUSAO
		AND C.TIPOITEMCONTAPAGAR = '05')

	-- Busca detalhamento de DARF para pagamento de IRF (do mes atual)
	LEFT JOIN (SELECT
			D.EMPRESA
		   ,D.UNIDADE
		   ,D.DATAEMISSAO
		   ,D.ANOMESBASE
		   ,SUM (D.LIQUIDOCOMPETENCIA) AS VALOR
		FROM RHDARFANALITICO D
		WHERE D.ESTABELECIMENTO = '00' + '01'
		AND D.TIPODARF = '1'  -- 1=IRF (pelo menos foi a conclusao a que cheguei, olhando os registros)
		AND D.ANOMESBASE = (SELECT	MAX(D2.ANOMESBASE)
			FROM RHDARFANALITICO D2
			WHERE D2.ESTABELECIMENTO = D.ESTABELECIMENTO
			AND D2.TIPODARF = D.TIPODARF)
		GROUP BY D.EMPRESA
				,D.UNIDADE
				,D.DATAEMISSAO
				,D.ANOMESBASE) AS DARF_IRF_MES
		ON (DARF_IRF_MES.EMPRESA = C.EMPRESA
		-- AND DARF_IRF_MES.UNIDADE = C.UNIDADE
		 AND DARF_IRF_MES.ANOMESBASE < C.DATAVENCIMENTO
		 AND DARF_IRF_MES.DATAEMISSAO < C.DATAINCLUSAO
		 AND C.TIPOITEMCONTAPAGAR = '04')


	-- Busca detalhamento de DARF para pagamento de IRF (mes seguinte)
	LEFT JOIN (SELECT
			D.EMPRESA
		   ,D.UNIDADE
		   ,D.DATAEMISSAO
		   ,D.ANOMESBASE
		   ,SUM (D.LIQUIDOCOMPETENCIA) AS VALOR
		FROM RHDARFANALITICO D
		WHERE D.ESTABELECIMENTO = '00' + '01'
		AND D.TIPODARF = '1'  -- 1=IRF (pelo menos foi a conclusao a que cheguei, olhando os registros)
		AND D.ANOMESBASE = (SELECT	MAX(D2.ANOMESBASE)
			FROM RHDARFANALITICO D2
			WHERE D2.ESTABELECIMENTO = D.ESTABELECIMENTO
			AND D2.TIPODARF = D.TIPODARF)
		GROUP BY D.EMPRESA
				,D.UNIDADE
				,D.DATAEMISSAO
				,D.ANOMESBASE) AS DARF_IRF_FUT
		ON (DARF_IRF_FUT.EMPRESA = C.EMPRESA
		-- AND DARF_IRF_FUT.UNIDADE = C.UNIDADE
		 AND DARF_IRF_FUT.ANOMESBASE < C.DATAVENCIMENTO
		 AND DARF_IRF_FUT.DATAEMISSAO > C.DATAINCLUSAO
		 AND C.TIPOITEMCONTAPAGAR = '04')

	WHERE C.EMPRESA = '00' + '01'
)
SELECT
	CTE.*
FROM CTE

GO


