USE [SIRH]
GO

/****** Object:  View [dbo].[VA_VTITULOS_CPAGAR3]    Script Date: 24/10/2023 08:30:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




-- Cooperativa Agroindustrial Nova Alianca Ltda
-- View para buscar dados de titulos a serem importados do Metadados pera o Protheus (titulos a pagar).
-- Autor: Robert Koch (com base em query do programa MetaFin.prw)
-- Data:  16/12/2020
--
-- Historico de alteracoes:
-- 09/08/2021 - Robert - Passa a buscar qualquer filial, inclusive NULL, para compatibilidade com query original do programa MetaFin.prw (GLPI 10667)
--                     - Renomeadas algumas colunas e formatadas datas para yyyyMMdd (GLPI 10667)
-- 09/03/2023 - Robert - Passa a buscar IRF por filial, da mesma forma que o PIS
-- 17/04/2023 - Robert - Saparadas colunas DarfIrfMes e DarfIrfFut
-- 23/10/2023 - Robert - Ajustes leitura IR (GLPI 9047)
--

ALTER VIEW [dbo].[VA_VTITULOS_CPAGAR3]
AS

-- COMO AS ORIGENS DOA VALORES SAO EM TABELAS DIFERENTES (APENAS A RHCONTASPAGARHIST 'ESTAH EM TODAS'), OPTEI POR FAZER COM UNION.
WITH CTE AS (

	-- Pagamentos simples, sem necessidade de ler outras tabelas
	SELECT 'RHCONTASPAGARHIST' AS ORIGEM
		, C.EMPRESA
		, C.DATAINCLUSAO
		, SUBSTRING(C.ESTABELECIMENTO, 3, 2) AS FILIAL
		, C.NROSEQUENCIAL
		, ISNULL (C.NROREMESSA, '') AS NROREMESSA
		, FORMAT (C.DATAINCLUSAO, 'yyyyMMdd') AS EMISSAO
		, FORMAT (C.DATAVENCIMENTO, 'yyyyMMdd') AS VENCTO
		, C.VALOR AS VALOR
		, ANOMESCOMPETENCIA
		, SUBSTRING(C.DESCRICAO20, 1, 6) AS FORNECE
		, RTRIM(C.DESCRICAO250) AS HIST
		, RTRIM(C.NUMERODOCUMENTO) AS NATUREZA
		, C.TIPOITEMCONTAPAGAR AS TPITEMCP
		, C.STATUSREGISTRO AS STATUSREG
		, C.TIPOITEMCONTAPAGAR
		, C.STATUSREGISTRO
	FROM RHCONTASPAGARHIST C
	WHERE C.EMPRESA = '00' + '01'
	AND C.TIPOITEMCONTAPAGAR not in ('22', '05', '04')  -- Tipos que serao tratados nas UNIONS a seguir.

	UNION ALL

	-- Depositos / remessas para bancos
	SELECT 'DEPOSITOS' AS ORIGEM
		, C.EMPRESA
		, C.DATAINCLUSAO
		, SUBSTRING(DEP.ESTABELECIMENTO, 3, 2) AS FILIAL
		, C.NROSEQUENCIAL
		, ISNULL (C.NROREMESSA, '') AS NROREMESSA
		, FORMAT (C.DATAINCLUSAO, 'yyyyMMdd') AS EMISSAO
		, FORMAT (C.DATAVENCIMENTO, 'yyyyMMdd') AS VENCTO
		, DEP.VALOR AS VALOR
		, ANOMESCOMPETENCIA
		, SUBSTRING(C.DESCRICAO20, 1, 6) AS FORNECE
		, RTRIM(C.DESCRICAO250) + ' (Rem.' + CAST(C.NROREMESSA AS VARCHAR) + ')' AS HIST
		, RTRIM(DEP.NUMERODOCUMENTO) AS NATUREZA
		, C.TIPOITEMCONTAPAGAR AS TPITEMCP
		, C.STATUSREGISTRO AS STATUSREG
		, C.TIPOITEMCONTAPAGAR
		, C.STATUSREGISTRO
	FROM RHCONTASPAGARHIST C
		-- Busca detalhamento de remessa para bancos.
		LEFT JOIN (SELECT EMPRESA
						, BANCO
						, NROREMESSA
						, ESTABELECIMENTO
						, NUMERODOCUMENTO
						, SUM(VALOR) AS VALOR
					FROM RHDEPOSITOSANALITICO
					WHERE EMPRESA = '00' + '01'
					GROUP BY EMPRESA, BANCO, NROREMESSA, ESTABELECIMENTO, NUMERODOCUMENTO) AS DEP
			ON (DEP.EMPRESA    = C.EMPRESA
			AND DEP.BANCO      = C.BANCO
			AND DEP.NROREMESSA = C.NROREMESSA)
	WHERE C.EMPRESA = '00' + '01'
	AND C.TIPOITEMCONTAPAGAR = '22'

	UNION ALL

	-- Pagamentos de PIS
	SELECT 'PIS' AS ORIGEM
		, C.EMPRESA
		, C.DATAINCLUSAO
		, SUBSTRING(DARF_PIS.UNIDADE, 3, 2) AS FILIAL
		, C.NROSEQUENCIAL
		, ISNULL (C.NROREMESSA, '') AS NROREMESSA
		, FORMAT (C.DATAINCLUSAO, 'yyyyMMdd') AS EMISSAO
		, FORMAT (C.DATAVENCIMENTO, 'yyyyMMdd') AS VENCTO
		, DARF_PIS.VALOR AS VALOR
		, ANOMESCOMPETENCIA
		, SUBSTRING(C.DESCRICAO20, 1, 6) AS FORNECE
		, RTRIM(C.DESCRICAO250) AS HIST
		, RTRIM(C.NUMERODOCUMENTO) AS NATUREZA
		, C.TIPOITEMCONTAPAGAR AS TPITEMCP
		, C.STATUSREGISTRO AS STATUSREG
		, C.TIPOITEMCONTAPAGAR
		, C.STATUSREGISTRO
	FROM RHCONTASPAGARHIST C
		-- Busca detalhamento de DARF para pagamento de PIS.
		-- Quando o RH gera os titulos de PIS antes do final do mes, a query abaixo nao os encontra (dataemissao > datainclusao). A solucao
		-- atual eh incluir manualmente no financeiro. Outra possibilidade seria desvincular os titulos de PIS desta rotina automatica
		-- e fazer a geracao atraves de um programa com parametrizacao manual do usuario, assim poderia gerar em qualquer data.
		LEFT JOIN (SELECT D.EMPRESA
						, D.UNIDADE
						, D.DATAEMISSAO
						, SUM (D.LIQUIDOCOMPETENCIA) AS VALOR
					FROM RHDARFANALITICO D
					WHERE D.ESTABELECIMENTO = '00' + '01'
					AND D.TIPODARF = '3'  -- 3=PIS
					AND D.DATAEMISSAO = (SELECT	MAX (D2.DATAEMISSAO)
										FROM RHDARFANALITICO D2
										WHERE D2.ESTABELECIMENTO = D.ESTABELECIMENTO
										AND D2.TIPODARF = D.TIPODARF)
					GROUP BY D.EMPRESA
							,D.UNIDADE
							,D.DATAEMISSAO) AS DARF_PIS
			ON (DARF_PIS.EMPRESA = C.EMPRESA
			AND DARF_PIS.DATAEMISSAO < C.DATAINCLUSAO)
	WHERE C.EMPRESA = '00' + '01'
	AND C.TIPOITEMCONTAPAGAR = '05'

	UNION ALL

	-- Pagamentos de IRF con vencimento no mes seguinte
	SELECT 'IRF_MES_MAIS_1' AS ORIGEM
		, C.EMPRESA
		, C.DATAINCLUSAO
		, SUBSTRING(DARF_IRF_MES.UNIDADE, 3, 2) AS FILIAL
		, C.NROSEQUENCIAL
		, ISNULL (C.NROREMESSA, '') AS NROREMESSA
		, FORMAT (C.DATAINCLUSAO, 'yyyyMMdd') AS EMISSAO
		, FORMAT (C.DATAVENCIMENTO, 'yyyyMMdd') AS VENCTO
		, DARF_IRF_MES.VALOR AS VALOR
		, ANOMESCOMPETENCIA
		, SUBSTRING(C.DESCRICAO20, 1, 6) AS FORNECE
		, RTRIM(C.DESCRICAO250) AS HIST
		, RTRIM(C.NUMERODOCUMENTO) AS NATUREZA
		, C.TIPOITEMCONTAPAGAR AS TPITEMCP
		, C.STATUSREGISTRO AS STATUSREG
		, C.TIPOITEMCONTAPAGAR
		, C.STATUSREGISTRO
	FROM RHCONTASPAGARHIST C
		JOIN (SELECT D.EMPRESA
					   , D.UNIDADE
					   , D.DATAEMISSAO
					   , D.ANOMESBASE
					   , SUM (D.LIQUIDOCOMPETENCIA) AS VALOR
					FROM RHDARFANALITICO D
					WHERE D.ESTABELECIMENTO = '00' + '01'
					AND D.TIPODARF = '1'  -- 1=IRF (pelo menos foi a conclusao a que cheguei, olhando os registros)
					GROUP BY D.EMPRESA
							,D.UNIDADE
							,D.DATAEMISSAO
							,D.ANOMESBASE) AS DARF_IRF_MES
					ON (DARF_IRF_MES.EMPRESA = C.EMPRESA
					 AND DARF_IRF_MES.ANOMESBASE = CAST (SUBSTRING (C.ANOMESCOMPETENCIA, 1, 4) + '-' + SUBSTRING (C.ANOMESCOMPETENCIA, 6, 2) + '-01 00:00:00' AS DATETIME)
				--	 AND DARF_IRF_MES.DATAEMISSAO < C.DATAINCLUSAO
			)
	WHERE C.EMPRESA = '00' + '01'
	AND C.TIPOITEMCONTAPAGAR = '04'
	/*
	UNION ALL

	-- Pagamentos de IRF com vencimento no mes seguinte + 1
	SELECT 'IRF_MES_MAIS_2' AS ORIGEM
		, C.EMPRESA
		, C.DATAINCLUSAO
		, SUBSTRING(DARF_IRF_FUT.UNIDADE, 3, 2) AS FILIAL
		, C.NROSEQUENCIAL
		, ISNULL (C.NROREMESSA, '') AS NROREMESSA
		, FORMAT (C.DATAINCLUSAO, 'yyyyMMdd') AS EMISSAO
		, FORMAT (C.DATAVENCIMENTO, 'yyyyMMdd') AS VENCTO
		, DARF_IRF_FUT.VALOR AS VALOR
		, SUBSTRING(C.DESCRICAO20, 1, 6) AS FORNECE
		, RTRIM(C.DESCRICAO250) AS HIST
		, RTRIM(C.NUMERODOCUMENTO) AS NATUREZA
		, C.TIPOITEMCONTAPAGAR AS TPITEMCP
		, C.STATUSREGISTRO AS STATUSREG
		, C.TIPOITEMCONTAPAGAR
		, C.STATUSREGISTRO
	FROM RHCONTASPAGARHIST C
		JOIN (SELECT D.EMPRESA
					   , D.UNIDADE
					   , D.DATAEMISSAO
					   , D.ANOMESBASE
					   , SUM (D.LIQUIDOCOMPETENCIA) AS VALOR
			FROM RHDARFANALITICO D
			WHERE D.ESTABELECIMENTO = '00' + '01'
			AND D.TIPODARF = '1'  -- 1=IRF (pelo menos foi a conclusao a que cheguei, olhando os registros)
			GROUP BY D.EMPRESA
					,D.UNIDADE
					,D.DATAEMISSAO
					,D.ANOMESBASE) AS DARF_IRF_FUT
			ON (DARF_IRF_FUT.EMPRESA = C.EMPRESA
--			 AND DARF_IRF_FUT.ANOMESBASE < C.DATAVENCIMENTO
			 AND DARF_IRF_FUT.ANOMESBASE = CAST (SUBSTRING (C.ANOMESCOMPETENCIA, 1, 4) + '-' + SUBSTRING (C.ANOMESCOMPETENCIA, 6, 2) + '-01 00:00:00' AS DATETIME)
			 AND DARF_IRF_FUT.DATAEMISSAO < C.DATAINCLUSAO
			 --AND DARF_IRF_FUT.DATAEMISSAO > C.DATAINCLUSAO
			 )
	WHERE C.EMPRESA = '00' + '01'
	AND C.TIPOITEMCONTAPAGAR = '04'
	*/
)
SELECT CTE.EMPRESA
	, CTE.DATAINCLUSAO
	, CTE.FILIAL
	, CTE.NROSEQUENCIAL
	, CTE.NROREMESSA
	, CTE.EMISSAO
	, CTE.VENCTO
	, CTE.VALOR
	, CTE.ANOMESCOMPETENCIA
	, CTE.FORNECE
	, CTE.HIST
	, CTE.NATUREZA
	, CTE.TPITEMCP
	,CASE CTE.TIPOITEMCONTAPAGAR
		WHEN '01' THEN 'GPS EMPRESA MENSAL'
		WHEN '04' THEN 'DARF IRF S/ SALARIOS'
		WHEN '05' THEN 'DARF PIS'
		WHEN '09' THEN 'CONTRATO'
		WHEN '10' THEN 'DARF IRF S/ AUTONOMOS'
		WHEN '13' THEN 'GPS DIFERENCA DISSIDIO'
		WHEN '16' THEN 'GFIP (FGTS 115)'
		WHEN '19' THEN 'GFIP (FGTS 650)'
		WHEN '22' THEN 'REMESSA P/BANCO'
		WHEN '26' THEN 'PENSIONISTAS'
		WHEN '40' THEN 'FOLHA AVULSA/RPA'
		WHEN '41' THEN 'FERIAS'
		WHEN '44' THEN 'RESCISAO PRINCIPAL'
		WHEN '45' THEN 'RESCISAO COMPLEMENTAR'
		WHEN '99' THEN 'OUTROS'
		ELSE ''
	END AS DESCR_TPITCP
	, CTE.STATUSREG
	,CASE CTE.STATUSREGISTRO
		WHEN '01' THEN 'INCLUIDO (AINDA NAO LIBERADO) NO METADADOS'
		WHEN '02' THEN 'LIBERADO (METADADOS) PARA O PROTHEUS IMPORTAR'
		WHEN '03' THEN 'ACEITO PELO PROTHEUS'
		WHEN '05' THEN 'EXCLUIDO NO PROTHEUS'
		WHEN '06' THEN 'EXCLUSAO NEGADA PELO PROTHEUS'
		WHEN '07' THEN 'EXCLUIDO NO METADADOS (AGUARDA EXCLUSAO PELO PROTHEUS)'
		WHEN '08' THEN 'REJEITADO PELO PROTHEUS'
		WHEN '10' THEN 'PROVISIONADO'
	END AS DESCR_STATUS
	, CTE.ORIGEM
FROM CTE

GO


