-- Robert - CONSULTAS RAPIDAS PARA COLLEONI REF. WANWAN - 24/11/2021

/*
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT * FROM SA3010 WHERE A3_NOME LIKE '%WAN%' OR A3_NOME LIKE '%ARMAZEM%'
select * FROM SA2010 WHERE A2_NOME LIKE '%WAN%' OR A2_NOME LIKE '%ARMAZEM%'
select * FROM SA2010 WHERE A2_COD IN ('000795','001675')
select * FROM SA1010 WHERE A1_CGC IN ('03808786000166', '08596790000121')
*/

/*  WANDERLEI COMO REPRESENTANTE:
SELECT F2_FILIAL AS FILIAL, dbo.VA_DTOC (F2_EMISSAO) AS EMISSAO, F2_DOC AS NF, F2_VEND1 AS VENDEDOR, F2_CLIENTE AS CLIENTE, F2_LOJA AS LOJA, RTRIM (A1_NOME) AS NOME_CLIENTE, F2_VALBRUT AS VALOR_BRUTO
FROM SF2010 SF2, SA1010 SA1
WHERE SF2.D_E_L_E_T_ = ''
AND F2_VEND1 IN ('080')
AND F2_TIPO NOT IN ('D', 'B')
AND SA1.D_E_L_E_T_ = ''
AND A1_FILIAL = '  '
AND A1_COD = F2_CLIENTE
AND A1_LOJA = F2_LOJA
ORDER BY F2_EMISSAO, F2_DOC
*/


WITH C AS (
    SELECT F2_FILIAL AS FILIAL, dbo.VA_DTOC (F2_EMISSAO) AS EMISSAO, F2_DOC AS NF
        , F2_VEND1 AS VENDEDOR, RTRIM (SA3.A3_NOME) AS NOME_VENDEDOR
        , F2_CLIENTE AS CLIENTE, F2_LOJA AS LOJA, RTRIM (A1_NOME) AS NOME_CLIENTE
        , F2_VALBRUT AS VALOR_BRUTO
        , isnull ((SELECT SUM (E3_COMIS) FROM SE3010 SE3
            WHERE D_E_L_E_T_ = ''
            AND E3_FILIAL = F2_FILIAL
            AND E3_VEND = F2_VEND1
            AND E3_NUM = F2_DOC
            AND E3_SERIE = F2_SERIE), 0) AS VLR_COMIS
    FROM SF2010 SF2, SA1010 SA1, SA3010 SA3
    WHERE SF2.D_E_L_E_T_ = ''
    AND (F2_VEND1 IN ('080','124','252') or F2_CLIENTE IN ('002927', '008590'))
    AND F2_TIPO NOT IN ('D', 'B')
    AND SA1.D_E_L_E_T_ = ''
    AND A1_FILIAL = '  '
    AND A1_COD = F2_CLIENTE
    AND A1_LOJA = F2_LOJA
    AND SA3.D_E_L_E_T_ = ''
    AND A3_FILIAL = '  '
    AND A3_COD = F2_VEND1
)
SELECT *, ROUND (VLR_COMIS * 100 / VALOR_BRUTO, 2) AS PERC_COMIS
FROM C
ORDER BY EMISSAO, NF

/*
SELECT E3_VEND, SUM (E3_COMIS)
FROM SE3010 SE3
WHERE D_E_L_E_T_ = ''
AND E3_VEND IN ('080','124','252')
GROUP BY E3_VEND
*/
-- WANDERLEI OU ARMAZEM DO VINHO COMO CLIENTE:
SELECT F2_FILIAL AS FILIAL, dbo.VA_DTOC (F2_EMISSAO) AS EMISSAO, F2_DOC AS NF, F2_VEND1 AS VENDEDOR, F2_CLIENTE AS CLIENTE, F2_LOJA AS LOJA, RTRIM (A1_NOME) AS NOME_CLIENTE, F2_VALBRUT AS VALOR_BRUTO
, (SELECT SUM (E1_VALOR) FROM SE1010 SE1 WHERE SE1.D_E_L_E_T_ = '' AND E1_FILIAL = F2_FILIAL AND E1_PREFIXO = F2_SERIE AND E1_NUM = F2_DOC) AS VLR_DUPLIC
, (SELECT STRING_AGG (D2_CF, ',') FROM SD2010 SD2 WHERE SD2.D_E_L_E_T_ = '' AND D2_FILIAL = F2_FILIAL AND D2_SERIE = F2_SERIE AND D2_DOC = F2_DOC) AS CFOPS
FROM SF2010 SF2, SA1010 SA1
WHERE SF2.D_E_L_E_T_ = ''
AND F2_CLIENTE IN ('002927', '008590')
AND F2_TIPO NOT IN ('D', 'B')
AND SA1.D_E_L_E_T_ = ''
AND A1_FILIAL = '  '
AND A1_COD = F2_CLIENTE
AND A1_LOJA = F2_LOJA
ORDER BY F2_EMISSAO, F2_DOC

/* NOTAS COMO FORNECEDORES (NOTAS DE COMISSAO):
SELECT F1_FILIAL AS FILIAL, dbo.VA_DTOC (F1_DTDIGIT) AS DT_DIGITACAO, F1_DOC AS NF, F1_FORNECE AS FORNECEDOR, F1_LOJA AS LOJA, RTRIM (A2_NOME) AS NOME_FORNECEDOR, F1_VALBRUT AS VALOR_BRUTO
FROM SF1010 SF1, SA2010 SA2
WHERE SF1.D_E_L_E_T_ = ''
AND F1_FORNECE IN ('000795','001675')
AND SA2.D_E_L_E_T_ = ''
AND A2_FILIAL = '  '
AND A2_COD = F1_FORNECE
AND A2_LOJA = F1_LOJA
ORDER BY F1_DTDIGIT, F1_DOC
*/
/*
SELECT E2_FILIAL AS FILIAL, dbo.VA_DTOC (E2_EMISSAO) AS EMISSAO, E2_NUM+E2_PARCELA AS TITULO, E2_PREFIXO AS PREFIXO, E2_FORNECE AS FORNECEDOR, E2_LOJA AS LOJA, RTRIM (E2_NOMFOR) AS NOME_FORNECEDOR, E2_VALOR AS VALOR
FROM SE2010 SE2
WHERE SE2.D_E_L_E_T_ = ''
AND E2_FORNECE IN ('000795','001675')
ORDER BY E2_EMISSAO, E2_NUM
*/
