SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Descricao: Retorna tabela para consulta de balancete consolidado (varias
--            filiais) e trazendo os 12 meses do ano (GLPI 8865).
--            Criado com base na consulta de mesmo nome do SQLServer Reporting Services.
-- Autor....: Robert Koch
-- Data.....: 25/07/2022
--
-- Historico de alteracoes:
--

ALTER FUNCTION VA_FBALANCETE_CONSOLIDADO
-- PARAMETROS DE CHAMADA
(
	@DATAINI   AS VARCHAR(8)
	,@DATAFIM  AS VARCHAR(8)
	,@FILINI   AS VARCHAR(2)
	,@FILFIM   AS VARCHAR(2)
	,@CONTAINI AS VARCHAR(20)
	,@CONTAFIM AS VARCHAR(20)
)
RETURNS TABLE
AS

NAO IMPLEMENTOU O FILTRO POR FILIAL
--INCLUIR DE VOLTA FILTRO POR MES INICIAL E FINAL
REFAZER LINHAS DE CONTAS SINTETICAS
MOSTRAR CONTA E DESCRICAO APENAS (ELIMINAR GRUPOS)

RETURN

-- MONTA TABELA DE CONTAS ANALITICAS X ANOS+MESES A LISTAR. COM ISSO SABE-SE TODAS AS CONTAS E TODOS OS MESES PARA OS QUAIS PRECISA BUSCAR DADOS.
WITH VALORES AS (
	SELECT M0_CODFIL,
		CT1_CONTA,
		CT1.CT1_DESC01,
		MESES.ANOMES,
		-- PARA CONTAS DE ATIVO (1,2 E 3), BUSCA VALOR (ULTIMA DATA IGUAL OU MENOR QUE O FINAL DE CADA PERIODO).
		-- PARA CONTAS DE RESULTADO (4 ACIMA), BUSCA MOVIMENTO.
		CASE WHEN SUBSTRING(CT1_CONTA, 1, 1) IN ('1', '2', '3')
			THEN (SELECT TOP 1 CQ1_DEBITO - CQ1_CREDIT
					FROM CQ1010 CQ1
					WHERE CQ1.D_E_L_E_T_ = ''
					AND CQ1.CQ1_TPSALD = '1'
					AND CQ1.CQ1_DATA <= MESES.ANOMES + '31'
					AND CQ1.CQ1_DATA <= @ANO + '1231'
					AND CQ1.CQ1_FILIAL = SM0.M0_CODFIL
					AND CQ1.CQ1_CONTA = CT1.CT1_CONTA
					ORDER BY CQ1_DATA DESC
				)
			ELSE (SELECT SUM(CQ1_DEBITO - CQ1_CREDIT)
					FROM CQ1010 CQ1
					WHERE CQ1.D_E_L_E_T_ = ''
					AND CQ1.CQ1_TPSALD = '1'
					AND CQ1.CQ1_DATA BETWEEN @ANO + '0101' AND @ANO + '1231'
					AND CQ1.CQ1_DATA BETWEEN MESES.ANOMES + '01' AND MESES.ANOMES +  '31'
					AND CQ1.CQ1_FILIAL = SM0.M0_CODFIL
					AND CQ1.CQ1_CONTA = CT1.CT1_CONTA
					AND CQ1.CQ1_LP != 'Z'  -- ZERAMENTO APURACAO LUCROS E PERDAS
				)
		END AS VALOR
	FROM SYS_COMPANY SM0,
		CT1010 CT1,
		(SELECT @ANO + '01' AS ANOMES
			UNION ALL
			SELECT @ANO + '02' AS ANOMES
			UNION ALL
			SELECT @ANO + '03' AS ANOMES
			UNION ALL
			SELECT @ANO + '04' AS ANOMES
			UNION ALL
			SELECT @ANO + '05' AS ANOMES
			UNION ALL
			SELECT @ANO + '06' AS ANOMES
			UNION ALL
			SELECT @ANO + '07' AS ANOMES
			UNION ALL
			SELECT @ANO + '08' AS ANOMES
			UNION ALL
			SELECT @ANO + '09' AS ANOMES
			UNION ALL
			SELECT @ANO + '10' AS ANOMES
			UNION ALL
			SELECT @ANO + '11' AS ANOMES
			UNION ALL
			SELECT @ANO + '12' AS ANOMES
		) AS MESES
	WHERE CT1.D_E_L_E_T_ = ''
		AND CT1.CT1_FILIAL = '  '
		AND CT1.CT1_CONTA BETWEEN @CONTAINI AND @CONTAFIM
		AND CT1.CT1_CLASSE = '2'
		AND SM0.D_E_L_E_T_ = ''
		AND SM0.M0_CODIGO = '01'
	)
SELECT SUBSTRING (VALORES.CT1_CONTA, 1, 1) AS GRUPO1
	,(SELECT CT1_GRP.CT1_DESC01
		FROM CT1010 CT1_GRP
		WHERE CT1_GRP.D_E_L_E_T_ = ''
		AND CT1_GRP.CT1_CONTA = SUBSTRING(VALORES.CT1_CONTA, 1, 1)
	) AS DESC_GRP1
	,SUBSTRING (VALORES.CT1_CONTA, 1, 3) AS GRUPO2
	,(SELECT CT1_GRP.CT1_DESC01
		FROM CT1010 CT1_GRP
		WHERE CT1_GRP.D_E_L_E_T_ = ''
		AND CT1_GRP.CT1_CONTA = SUBSTRING(VALORES.CT1_CONTA, 1, 3)
	) AS DESC_GRP2
	,SUBSTRING (VALORES.CT1_CONTA, 1, 5) AS GRUPO3
	,(SELECT CT1_GRP.CT1_DESC01
		FROM CT1010 CT1_GRP
		WHERE CT1_GRP.D_E_L_E_T_ = ''
		AND CT1_GRP.CT1_CONTA = SUBSTRING(VALORES.CT1_CONTA, 1, 5)
	) AS DESC_GRP3
	,SUBSTRING (VALORES.CT1_CONTA, 1, 7) AS GRUPO4
	,(SELECT CT1_GRP.CT1_DESC01
		FROM CT1010 CT1_GRP
		WHERE CT1_GRP.D_E_L_E_T_ = ''
		AND CT1_GRP.CT1_CONTA = SUBSTRING(VALORES.CT1_CONTA, 1, 7)
	) AS DESC_GRP4
	,SUBSTRING (VALORES.CT1_CONTA, 1, 9) AS GRUPO5
	,(SELECT CT1_GRP.CT1_DESC01
		FROM CT1010 CT1_GRP
		WHERE CT1_GRP.D_E_L_E_T_ = ''
		AND CT1_GRP.CT1_CONTA = SUBSTRING(VALORES.CT1_CONTA, 1, 9)
	) AS DESC_GRP5
	,VALORES.CT1_CONTA AS CONTA
	,(SELECT CT1_GRP.CT1_DESC01
		FROM CT1010 CT1_GRP
		WHERE CT1_GRP.D_E_L_E_T_ = ''
		AND CT1_GRP.CT1_CONTA = VALORES.CT1_CONTA
	) AS DESC_CONTA
	,VALORES.M0_CODFIL AS FILIAL
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '01' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR01
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '02' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR02
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '03' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR03
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '04' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR04
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '05' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR05
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '06' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR06
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '07' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR07
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '08' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR08
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '09' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR09
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '10' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR10
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '11' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR11
	,ISNULL (SUM (CASE SUBSTRING (VALORES.ANOMES, 5, 2) WHEN '12' THEN VALORES.VALOR ELSE 0 END), 0) AS VLR12
FROM VALORES
GROUP BY VALORES.CT1_CONTA
	,VALORES.M0_CODFIL
