DECLARE @FILINI VARCHAR (2) = '01';
DECLARE @FILFIM VARCHAR (2) = '01';
DECLARE @DATAINI VARCHAR (8) = '20220501';
DECLARE @DATAFIM VARCHAR (8) = '20220531';
DECLARE @OPINI VARCHAR (14) = ''--'12247201001';
DECLARE @OPFIM VARCHAR (14) = 'Z'--'12247201001';
-- 12429101006 -- terceirizacao
-- 22013000001 -- perda
-- 11925201001 -- troca de material
-- 12247201001 -- por que o copmponenet 1540 aparece 4 vezes? e o 3218 aparece mais ainda

-- MONTA LISTA DE FILIAIS E NUMEROS DE OP
;WITH LISTA_DE_OP_1 AS (
SELECT C2_FILIAL AS FILIAL, C2_NUM + SC2.C2_ITEM + SC2.C2_SEQUEN + SC2.C2_ITEMGRD AS OP
FROM SC2010 SC2
WHERE SC2.D_E_L_E_T_ = ''
 AND SC2.C2_FILIAL BETWEEN @FILINI AND @FILFIM
 AND C2_NUM + SC2.C2_ITEM + SC2.C2_SEQUEN + SC2.C2_ITEMGRD BETWEEN @OPINI AND @OPFIM
 
 -- BUSCA O MAIOR/MENOR VALOR ENTRE DUAS DATAS. ROYALTIES PARA https://stackoverflow.com/questions/124417/is-there-a-max-function-in-sql-server-that-takes-two-values-like-math-max-in-ne
 AND (SELECT MAX (DIA) FROM (VALUES (SC2.C2_EMISSAO), (SC2.C2_DATPRI)) AS UM_NOME_DE_TABELA_QUALQUER (DIA)) >= @DATAINI
 AND (SELECT MIN (DIA) FROM (VALUES (SC2.C2_DATPRF), (SC2.C2_DATRF)) AS UM_NOME_DE_TABELA_QUALQUER (DIA)) <= @DATAFIM
UNION
SELECT DISTINCT D3_FILIAL, D3_OP
FROM SD3010 SD3
WHERE SD3.D_E_L_E_T_ = ''
AND SD3.D3_OP != ''
AND SD3.D3_OP BETWEEN @OPINI AND @OPFIM
AND SD3.D3_EMISSAO BETWEEN @DATAINI AND @DATAFIM
)
--SELECT * FROM LISTA_DE_OP
, LISTA_DE_OP AS (
SELECT LISTA_DE_OP_1.*, B1_QB, SC2.C2_PRODUTO, C2_VALINEN, SC2.C2_DATPRI, SC2.C2_REVISAO, SC2.C2_QUJE, SC2.C2_PERDA
FROM LISTA_DE_OP_1, SC2010 SC2, SB1010 SB1
WHERE SC2.D_E_L_E_T_ = ''
AND SC2.C2_FILIAL = LISTA_DE_OP_1.FILIAL
AND SC2.C2_NUM     = SUBSTRING (LISTA_DE_OP_1.OP, 1, 6)
AND SC2.C2_ITEM    = SUBSTRING (LISTA_DE_OP_1.OP, 7, 2)
AND SC2.C2_SEQUEN  = SUBSTRING (LISTA_DE_OP_1.OP, 9, 3)
AND SC2.C2_ITEMGRD = SUBSTRING (LISTA_DE_OP_1.OP, 12, 2)
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_FILIAL = '  '
AND SB1.B1_COD = SC2.C2_PRODUTO
)
--SELECT * FROM LISTA_DE_OP

, MOVTOS AS (
SELECT SD3.D3_FILIAL, SD3.D3_OP, SD3.D3_COD, B1_DESC, B1_UM,
     SUM (CASE WHEN D3_CF IN ('PR0', 'PR1') THEN SD3.D3_QUANT ELSE 0 END
          ) AS PRODUCAO_QT,
     SUM (CASE WHEN D3_CF IN ('RE1', 'RE2', 'RE5', 'RE9') THEN SD3.D3_QUANT ELSE 0 END +
          CASE WHEN D3_CF IN ('DE1', 'DE2', 'DE5', 'DE9') THEN SD3.D3_QUANT * -1 ELSE 0 END
          ) AS REQAUT_QT,
     SUM (CASE WHEN SD3.D3_VAPEROP != 'S' AND D3_CF IN ('RE0', 'RE3', 'RE6') THEN SD3.D3_QUANT ELSE 0 END +
          CASE WHEN SD3.D3_VAPEROP != 'S' AND D3_CF IN ('DE0', 'DE3', 'DE6') THEN SD3.D3_QUANT * -1 ELSE 0 END
         ) AS REQMAN_QT,
     SUM (CASE WHEN SD3.D3_VAPEROP = 'S' THEN SD3.D3_QUANT ELSE 0 END
		) AS PERDA_QT,
     SUM (CASE WHEN D3_CF IN ('PR0', 'PR1') THEN SD3.D3_CUSTO1 ELSE 0 END
          ) AS PRODUCAO_VL,
     SUM (CASE WHEN D3_CF IN ('RE1', 'RE2', 'RE5', 'RE9') THEN SD3.D3_CUSTO1 ELSE 0 END +
          CASE WHEN D3_CF IN ('DE1', 'DE2', 'DE5', 'DE9') THEN SD3.D3_CUSTO1 * -1 ELSE 0 END
          ) AS REQAUT_VL,
     SUM (CASE WHEN SD3.D3_VAPEROP != 'S' AND D3_CF IN ('RE0', 'RE3', 'RE6') THEN SD3.D3_CUSTO1 ELSE 0 END +
          CASE WHEN SD3.D3_VAPEROP != 'S' AND D3_CF IN ('DE0', 'DE3', 'DE6') THEN SD3.D3_CUSTO1 * -1 ELSE 0 END
         ) AS REQMAN_VL,
     SUM (CASE WHEN SD3.D3_VAPEROP = 'S' THEN SD3.D3_CUSTO1 ELSE 0 END
		) AS PERDA_VL
 FROM SD3010 SD3, SB1010 SB1
       WHERE SD3.D_E_L_E_T_ != '*' 
         AND SD3.D3_ESTORNO != 'S'
		 AND EXISTS (SELECT *
					FROM LISTA_DE_OP
					WHERE LISTA_DE_OP.FILIAL = SD3.D3_FILIAL
					AND LISTA_DE_OP.OP = SD3.D3_OP)
		 AND SD3.D3_EMISSAO BETWEEN @DATAINI AND @DATAFIM
and SB1.D_E_L_E_T_ != '*' 
AND SB1.B1_FILIAL   = '  '
AND SB1.B1_COD      = SD3.D3_COD
GROUP BY SD3.D3_FILIAL, SD3.D3_OP, SD3.D3_COD, SB1.B1_DESC, B1_UM
)
--SELECT * FROM MOVTOS

, ESTRUT AS (
SELECT FILIAL, OP --C2_FILIAL, C2_NUM + SC2.C2_ITEM + SC2.C2_SEQUEN + SC2.C2_ITEMGRD AS OP_SC2
	, C2_PRODUTO, C2_VALINEN, G1_COMP, SB1_COMP.B1_DESC, SB1_COMP.B1_UM
    , SUM (CASE SG1.G1_FIXVAR
               WHEN 'V' THEN SG1.G1_QUANT / CASE LISTA_DE_OP.B1_QB WHEN 0 THEN 1 ELSE LISTA_DE_OP.B1_QB END + SG1.G1_QUANT * SG1.G1_PERDA / 100
               ELSE SG1.G1_QUANT + SG1.G1_QUANT * SG1.G1_PERDA / 100
          END) * SUM (LISTA_DE_OP.C2_QUJE + LISTA_DE_OP.C2_PERDA) AS QT_ESTRU
 FROM LISTA_DE_OP
	, SG1010 SG1, SB1010 SB1_COMP, SB1010 SB1_FINAL --, SC2010 SC2
WHERE SB1_COMP.D_E_L_E_T_ <> '*' 
 AND SB1_COMP.B1_FILIAL   = '  ' 
 AND SB1_COMP.B1_COD      = SG1.G1_COMP
 AND SB1_COMP.B1_FANTASM != 'S'
 AND SG1.D_E_L_E_T_ <> '*' 
 AND SG1.G1_FILIAL   = '  '
 AND SG1.G1_COD      = LISTA_DE_OP.C2_PRODUTO
 AND SG1.G1_INI     <= LISTA_DE_OP.C2_DATPRI AND SG1.G1_FIM >= LISTA_DE_OP.C2_DATPRI
 AND SG1.G1_REVINI  <= LISTA_DE_OP.C2_REVISAO AND SG1.G1_REVFIM >= LISTA_DE_OP.C2_REVISAO
 GROUP BY LISTA_DE_OP.FILIAL, LISTA_DE_OP.OP, LISTA_DE_OP.C2_PRODUTO, LISTA_DE_OP.C2_VALINEN, SG1.G1_COMP, SB1_COMP.B1_DESC, SB1_COMP.B1_UM
)
--SELECT * FROM ESTRUT
, ACUMULADO AS (
SELECT ISNULL (MOVTOS.D3_FILIAL, ESTRUT.FILIAL) AS FILIAL
	, ISNULL (MOVTOS.D3_OP, ESTRUT.OP) AS OP
	, ISNULL (MOVTOS.D3_COD, ESTRUT.G1_COMP) AS COMP
	, ISNULL (MOVTOS.B1_DESC, ESTRUT.B1_DESC) AS DESCR_COMP
	, ISNULL (MOVTOS.B1_UM, ESTRUT.B1_UM) AS UM_COMP
	, ISNULL (MOVTOS.PRODUCAO_QT, 0) AS PRODUCAO_QT
	, ISNULL (MOVTOS.REQAUT_QT, 0) AS REQAUT_QT
	, ISNULL (MOVTOS.REQMAN_QT, 0) AS REQMAN_QT
	, ISNULL (MOVTOS.PERDA_QT, 0) AS PERDA_QT
	, ISNULL (MOVTOS.PRODUCAO_VL, 0) AS PRODUCAO_VL
	, ISNULL (MOVTOS.REQAUT_VL, 0) AS REQAUT_VL
	, ISNULL (MOVTOS.REQMAN_VL, 0) AS REQMAN_VL
	, ISNULL (MOVTOS.PERDA_VL, 0) AS PERDA_VL
	, ISNULL (ESTRUT.QT_ESTRU, 0) AS QT_ESTRU
	, ESTRUT.C2_VALINEN
--	, MOVTOS.*
--	, ESTRUT.*
FROM MOVTOS
FULL OUTER JOIN ESTRUT
ON (G1_COMP = D3_COD)
)
SELECT * FROM ACUMULADO
/*
SELECT ACUMULADO.*
	, REQAUT_QT + REQMAN_QT + PERDA_QT AS CONSUMO_TOTAL
	, REQAUT_QT + REQMAN_QT + PERDA_QT - QT_ESTRU AS VARIACAO_QT
	, SH1.H1_DESCRI AS LINHA_PREVISTA
FROM ACUMULADO
 LEFT JOIN SH1010 SH1
ON (SH1.D_E_L_E_T_ = ''
AND SH1.H1_FILIAL = '  '
AND SH1.H1_CODIGO = ACUMULADO.C2_VALINEN)
ORDER BY FILIAL, OP, COMP
*/
