-- VIEW CRIADA PARA O pEDRO MONTAR CONSULTA INICIAL EM POWERBI. A INTENCAO EH, DEPOIS, OPERAR COM VIEWS.

ALTER VIEW VA_VPBI_SD3
AS 
SELECT * FROM SD3010 
WHERE D_E_L_E_T_ = ''
AND D3_FILIAL = '01'
AND D3_EMISSAO >= FORMAT (DATEADD (MONTH, -1, GETDATE ()), 'yyyyMMdd')

SELECT * FROM VA_VPBI_SD3
