USE [BL01]
GO

/****** Object:  Table [dbo].[SQL_BL01_TABLE]    Script Date: 05/02/2021 07:59:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SQL_BL01_TABLE](
	[ZZA_FILIAL] [nvarchar](2) NULL,
	[ZZA_SAFRA] [nvarchar](4) NULL,
	[ZZA_CARGA] [nvarchar](4) NULL,
	[ZZA_PRODUT] [nvarchar](15) NULL,
	[DATA_VALUE] [float] NULL,
	[DATA_NUMBER] [nvarchar](20) NULL,
	[LINE_SELECTED] [int] NULL,
	[PRODUCT_NAME] [nvarchar](40) NULL,
	[PRODUCER_NAME] [nvarchar](50) NULL,
	[RESULT] [real] NULL,
	[SAMPLES_NUMBER] [int] NULL,
	[MEASURE_SCALE] [smallint] NULL,
	[MEASURE_NAME] [nvarchar](10) NULL,
UNIQUE CLUSTERED 
(
	[ZZA_FILIAL] ASC,
	[ZZA_SAFRA] ASC,
	[ZZA_CARGA] ASC,
	[ZZA_PRODUT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [BL01]
GO

/****** Object:  Table [dbo].[SQL_BL01_SAMPLES]    Script Date: 05/02/2021 07:59:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SQL_BL01_SAMPLES](
	[ZZA_FILIAL] [nvarchar](2) NOT NULL,
	[ZZA_SAFRA] [nvarchar](4) NOT NULL,
	[ZZA_CARGA] [nvarchar](4) NOT NULL,
	[ZZA_PRODUT] [nvarchar](15) NOT NULL,
	[SAMPLE] [int] NOT NULL,
	[RESULT] [real] NULL,
UNIQUE CLUSTERED 
(
	[ZZA_FILIAL] ASC,
	[ZZA_SAFRA] ASC,
	[ZZA_CARGA] ASC,
	[ZZA_PRODUT] ASC,
	[SAMPLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [BL01]
GO

/****** Object:  Table [dbo].[MEDICOES_CONTINUAS]    Script Date: 05/02/2021 08:00:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MEDICOES_CONTINUAS](
	[FILIAL] [varchar](2) NOT NULL,
	[LINHA] [int] NOT NULL,
	[HORA] [datetime] NOT NULL,
	[LINE_STATUS] [varchar](6) NOT NULL,
	[GRAU] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[FILIAL] ASC,
	[LINHA] ASC,
	[HORA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


