SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[VPBI_REPRESENTANTES]  -- REPRESENTANTES
AS 
SELECT A3_COD
	, A3_NOME
	, A3_VAGEREN  -- GERENTE / SUPERVISOR - VINCULADO A ESTA MESMA TABELA
FROM protheus.dbo.SA3010
WHERE D_E_L_E_T_ = ''
AND A3_FILIAL = '  '
GO
