SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[VPBI_CLIENTES]  -- CLIENTES
AS 
SELECT A1_COD
	, A1_LOJA
	, A1_NOME
	, A1_EST      -- ESTADO (UF)
	, A1_REGIAO   -- REGIAO
	, A1_MESO     -- MESOREGIAO
	, A1_COD_MUN  -- CODIGO MUNICIPIO IBGE
FROM protheus.dbo.SA1010
WHERE D_E_L_E_T_ = ''
AND A1_FILIAL = '  '
GO
